// CIEfinder by DoctoriZe
// Base de datos integrada de códigos CIE-9 (ICD-9-CM) y CIE-10, bilingüe ES/EN.
// CIE-10: 145 códigos de uso frecuente en consulta clínica.
// CIE-9: 698 códigos, incorporando el manual de codificación CIE-9 reducido
// (diagnósticos, consultas, causas externas y procedimientos). Fuente en español;
// donde no había traducción oficial al inglés se usa el nombre en español como respaldo.
// Desde Ajustes > Importar catálogo se puede ampliar o actualizar con más códigos
// (por ejemplo, el catálogo completo de la OMS, el CDC o el ministerio de salud local)
// sin perder los datos ya guardados (historial y favoritos).

const CIE_BASE_DATA = [
  // ---- CIE-10 ----
  { code: "A00", sys: "CIE10", es: "Cólera", en: "Cholera" },
  { code: "A01.0", sys: "CIE10", es: "Fiebre tifoidea", en: "Typhoid fever" },
  { code: "A09", sys: "CIE10", es: "Diarrea y gastroenteritis de presunto origen infeccioso", en: "Infectious gastroenteritis and colitis, unspecified" },
  { code: "A15", sys: "CIE10", es: "Tuberculosis respiratoria, confirmada bacteriológica e histológicamente", en: "Respiratory tuberculosis, bacteriologically confirmed" },
  { code: "A41.9", sys: "CIE10", es: "Sepsis, no especificada", en: "Sepsis, unspecified organism" },
  { code: "A90", sys: "CIE10", es: "Fiebre del dengue", en: "Dengue fever" },
  { code: "A91", sys: "CIE10", es: "Fiebre hemorrágica del dengue", en: "Dengue hemorrhagic fever" },
  { code: "B01.9", sys: "CIE10", es: "Varicela, sin complicaciones", en: "Varicella without complication" },
  { code: "B02.9", sys: "CIE10", es: "Herpes zóster, sin complicaciones", en: "Zoster without complications" },
  { code: "B05.9", sys: "CIE10", es: "Sarampión, sin complicaciones", en: "Measles without complication" },
  { code: "B15", sys: "CIE10", es: "Hepatitis aguda tipo A", en: "Acute hepatitis A" },
  { code: "B16", sys: "CIE10", es: "Hepatitis aguda tipo B", en: "Acute hepatitis B" },
  { code: "B18.2", sys: "CIE10", es: "Hepatitis viral crónica tipo C", en: "Chronic viral hepatitis C" },
  { code: "B20", sys: "CIE10", es: "Enfermedad por VIH", en: "HIV disease" },
  { code: "B34.9", sys: "CIE10", es: "Infección viral, no especificada", en: "Viral infection, unspecified" },
  { code: "B35.0", sys: "CIE10", es: "Tiña de la barba y del cuero cabelludo", en: "Tinea barbae and tinea capitis" },
  { code: "B37.0", sys: "CIE10", es: "Candidiasis estomatitis", en: "Candidal stomatitis" },
  { code: "B82.9", sys: "CIE10", es: "Parasitosis intestinal, no especificada", en: "Intestinal parasitism, unspecified" },
  { code: "C16.9", sys: "CIE10", es: "Tumor maligno del estómago, no especificado", en: "Malignant neoplasm of stomach, unspecified" },
  { code: "C18.9", sys: "CIE10", es: "Tumor maligno del colon, no especificado", en: "Malignant neoplasm of colon, unspecified" },
  { code: "C34.9", sys: "CIE10", es: "Tumor maligno de bronquio o pulmón, no especificado", en: "Malignant neoplasm of bronchus or lung, unspecified" },
  { code: "C50.9", sys: "CIE10", es: "Tumor maligno de mama, no especificado", en: "Malignant neoplasm of breast, unspecified" },
  { code: "C53.9", sys: "CIE10", es: "Tumor maligno del cuello uterino, no especificado", en: "Malignant neoplasm of cervix uteri, unspecified" },
  { code: "C61", sys: "CIE10", es: "Tumor maligno de la próstata", en: "Malignant neoplasm of prostate" },
  { code: "C71.9", sys: "CIE10", es: "Tumor maligno del encéfalo, no especificado", en: "Malignant neoplasm of brain, unspecified" },
  { code: "C91.0", sys: "CIE10", es: "Leucemia linfoblástica aguda", en: "Acute lymphoblastic leukemia" },
  { code: "D50.9", sys: "CIE10", es: "Anemia por deficiencia de hierro, no especificada", en: "Iron deficiency anemia, unspecified" },
  { code: "D64.9", sys: "CIE10", es: "Anemia, no especificada", en: "Anemia, unspecified" },
  { code: "E03.9", sys: "CIE10", es: "Hipotiroidismo, no especificado", en: "Hypothyroidism, unspecified" },
  { code: "E05.9", sys: "CIE10", es: "Tirotoxicosis, no especificada", en: "Thyrotoxicosis, unspecified" },
  { code: "E10", sys: "CIE10", es: "Diabetes mellitus tipo 1", en: "Type 1 diabetes mellitus" },
  { code: "E11", sys: "CIE10", es: "Diabetes mellitus tipo 2", en: "Type 2 diabetes mellitus" },
  { code: "E11.9", sys: "CIE10", es: "Diabetes mellitus tipo 2, sin complicaciones", en: "Type 2 diabetes mellitus without complications" },
  { code: "E66.9", sys: "CIE10", es: "Obesidad, no especificada", en: "Obesity, unspecified" },
  { code: "E78.5", sys: "CIE10", es: "Hiperlipidemia, no especificada", en: "Hyperlipidemia, unspecified" },
  { code: "E86", sys: "CIE10", es: "Depleción del volumen (deshidratación)", en: "Volume depletion" },
  { code: "E87.6", sys: "CIE10", es: "Hipopotasemia", en: "Hypokalemia" },
  { code: "F10.9", sys: "CIE10", es: "Trastornos mentales y del comportamiento por uso de alcohol", en: "Alcohol use disorder, unspecified" },
  { code: "F20.9", sys: "CIE10", es: "Esquizofrenia, no especificada", en: "Schizophrenia, unspecified" },
  { code: "F31.9", sys: "CIE10", es: "Trastorno afectivo bipolar, no especificado", en: "Bipolar disorder, unspecified" },
  { code: "F32.9", sys: "CIE10", es: "Episodio depresivo, no especificado", en: "Major depressive disorder, single episode, unspecified" },
  { code: "F33.9", sys: "CIE10", es: "Trastorno depresivo recurrente, no especificado", en: "Major depressive disorder, recurrent, unspecified" },
  { code: "F41.1", sys: "CIE10", es: "Trastorno de ansiedad generalizada", en: "Generalized anxiety disorder" },
  { code: "F41.9", sys: "CIE10", es: "Trastorno de ansiedad, no especificado", en: "Anxiety disorder, unspecified" },
  { code: "F43.1", sys: "CIE10", es: "Trastorno de estrés postraumático", en: "Post-traumatic stress disorder" },
  { code: "F84.0", sys: "CIE10", es: "Autismo infantil", en: "Autistic disorder" },
  { code: "F90.9", sys: "CIE10", es: "Trastorno hiperquinético, no especificado (TDAH)", en: "Attention-deficit hyperactivity disorder, unspecified type" },
  { code: "G20", sys: "CIE10", es: "Enfermedad de Parkinson", en: "Parkinson's disease" },
  { code: "G30.9", sys: "CIE10", es: "Enfermedad de Alzheimer, no especificada", en: "Alzheimer's disease, unspecified" },
  { code: "G35", sys: "CIE10", es: "Esclerosis múltiple", en: "Multiple sclerosis" },
  { code: "G40.9", sys: "CIE10", es: "Epilepsia, no especificada", en: "Epilepsy, unspecified" },
  { code: "G43.9", sys: "CIE10", es: "Migraña, no especificada", en: "Migraine, unspecified" },
  { code: "G47.00", sys: "CIE10", es: "Insomnio, no especificado", en: "Insomnia, unspecified" },
  { code: "G50.0", sys: "CIE10", es: "Neuralgia del trigémino", en: "Trigeminal neuralgia" },
  { code: "H10.9", sys: "CIE10", es: "Conjuntivitis, no especificada", en: "Conjunctivitis, unspecified" },
  { code: "H25.9", sys: "CIE10", es: "Catarata senil, no especificada", en: "Age-related cataract, unspecified" },
  { code: "H40.9", sys: "CIE10", es: "Glaucoma, no especificado", en: "Glaucoma, unspecified" },
  { code: "H52.4", sys: "CIE10", es: "Presbicia", en: "Presbyopia" },
  { code: "H60.9", sys: "CIE10", es: "Otitis externa, no especificada", en: "Otitis externa, unspecified" },
  { code: "H66.9", sys: "CIE10", es: "Otitis media, no especificada", en: "Otitis media, unspecified" },
  { code: "H81.1", sys: "CIE10", es: "Vértigo posicional paroxístico benigno", en: "Benign paroxysmal vertigo" },
  { code: "H93.1", sys: "CIE10", es: "Tinnitus (acúfenos)", en: "Tinnitus" },
  { code: "I10", sys: "CIE10", es: "Hipertensión esencial (primaria)", en: "Essential (primary) hypertension" },
  { code: "I21.9", sys: "CIE10", es: "Infarto agudo de miocardio, no especificado", en: "Acute myocardial infarction, unspecified" },
  { code: "I25.9", sys: "CIE10", es: "Enfermedad isquémica crónica del corazón, no especificada", en: "Chronic ischemic heart disease, unspecified" },
  { code: "I48.9", sys: "CIE10", es: "Fibrilación y flutter auricular, no especificado", en: "Atrial fibrillation and flutter, unspecified" },
  { code: "I50.9", sys: "CIE10", es: "Insuficiencia cardíaca, no especificada", en: "Heart failure, unspecified" },
  { code: "I63.9", sys: "CIE10", es: "Infarto cerebral, no especificado", en: "Cerebral infarction, unspecified" },
  { code: "I64", sys: "CIE10", es: "Accidente vascular encefálico agudo, no especificado como hemorrágico o isquémico", en: "Stroke, not specified as hemorrhage or infarction" },
  { code: "I80.9", sys: "CIE10", es: "Flebitis y tromboflebitis, no especificada", en: "Phlebitis and thrombophlebitis, unspecified" },
  { code: "I83.9", sys: "CIE10", es: "Várices de miembros inferiores, sin úlcera ni inflamación", en: "Varicose veins of lower extremities without ulcer or inflammation" },
  { code: "J00", sys: "CIE10", es: "Rinofaringitis aguda (resfriado común)", en: "Acute nasopharyngitis (common cold)" },
  { code: "J02.9", sys: "CIE10", es: "Faringitis aguda, no especificada", en: "Acute pharyngitis, unspecified" },
  { code: "J03.9", sys: "CIE10", es: "Amigdalitis aguda, no especificada", en: "Acute tonsillitis, unspecified" },
  { code: "J06.9", sys: "CIE10", es: "Infección aguda de las vías respiratorias superiores, no especificada", en: "Acute upper respiratory infection, unspecified" },
  { code: "J18.9", sys: "CIE10", es: "Neumonía, no especificada", en: "Pneumonia, unspecified organism" },
  { code: "J20.9", sys: "CIE10", es: "Bronquitis aguda, no especificada", en: "Acute bronchitis, unspecified" },
  { code: "J30.4", sys: "CIE10", es: "Rinitis alérgica, no especificada", en: "Allergic rhinitis, unspecified" },
  { code: "J34.9", sys: "CIE10", es: "Trastorno de la nariz y de los senos paranasales, no especificado", en: "Disease of nose and nasal sinuses, unspecified" },
  { code: "J44.9", sys: "CIE10", es: "Enfermedad pulmonar obstructiva crónica, no especificada", en: "Chronic obstructive pulmonary disease, unspecified" },
  { code: "J45.9", sys: "CIE10", es: "Asma, no especificada", en: "Asthma, unspecified" },
  { code: "K02.9", sys: "CIE10", es: "Caries dental, no especificada", en: "Dental caries, unspecified" },
  { code: "K21.9", sys: "CIE10", es: "Enfermedad por reflujo gastroesofágico sin esofagitis", en: "Gastro-esophageal reflux disease without esophagitis" },
  { code: "K25.9", sys: "CIE10", es: "Úlcera gástrica, no especificada", en: "Gastric ulcer, unspecified" },
  { code: "K29.7", sys: "CIE10", es: "Gastritis, no especificada", en: "Gastritis, unspecified" },
  { code: "K35.80", sys: "CIE10", es: "Apendicitis aguda, no especificada", en: "Unspecified acute appendicitis" },
  { code: "K40.9", sys: "CIE10", es: "Hernia inguinal, no especificada", en: "Unspecified inguinal hernia" },
  { code: "K52.9", sys: "CIE10", es: "Gastroenteritis y colitis no infecciosa, no especificada", en: "Noninfective gastroenteritis and colitis, unspecified" },
  { code: "K59.0", sys: "CIE10", es: "Constipación (estreñimiento)", en: "Constipation" },
  { code: "K70.3", sys: "CIE10", es: "Cirrosis hepática alcohólica", en: "Alcoholic cirrhosis of liver" },
  { code: "K80.2", sys: "CIE10", es: "Cálculo de la vesícula biliar sin colecistitis", en: "Gallstone without cholecystitis" },
  { code: "L03.90", sys: "CIE10", es: "Celulitis, no especificada", en: "Cellulitis, unspecified" },
  { code: "L20.9", sys: "CIE10", es: "Dermatitis atópica, no especificada", en: "Atopic dermatitis, unspecified" },
  { code: "L23.9", sys: "CIE10", es: "Dermatitis alérgica de contacto, causa no especificada", en: "Allergic contact dermatitis, unspecified cause" },
  { code: "L30.9", sys: "CIE10", es: "Dermatitis, no especificada", en: "Dermatitis, unspecified" },
  { code: "L40.9", sys: "CIE10", es: "Psoriasis, no especificada", en: "Psoriasis, unspecified" },
  { code: "L50.9", sys: "CIE10", es: "Urticaria, no especificada", en: "Urticaria, unspecified" },
  { code: "L70.9", sys: "CIE10", es: "Acné, no especificado", en: "Acne, unspecified" },
  { code: "M06.9", sys: "CIE10", es: "Artritis reumatoide, no especificada", en: "Rheumatoid arthritis, unspecified" },
  { code: "M15.9", sys: "CIE10", es: "Poliartrosis, no especificada", en: "Polyosteoarthritis, unspecified" },
  { code: "M17.9", sys: "CIE10", es: "Gonartrosis (artrosis de la rodilla), no especificada", en: "Osteoarthritis of knee, unspecified" },
  { code: "M19.90", sys: "CIE10", es: "Artrosis, no especificada", en: "Osteoarthritis, unspecified site" },
  { code: "M25.50", sys: "CIE10", es: "Dolor en articulación, no especificado", en: "Pain in unspecified joint" },
  { code: "M54.5", sys: "CIE10", es: "Lumbago (dolor lumbar bajo)", en: "Low back pain" },
  { code: "M54.9", sys: "CIE10", es: "Dorsalgia, no especificada", en: "Dorsalgia, unspecified" },
  { code: "M81.9", sys: "CIE10", es: "Osteoporosis, no especificada", en: "Osteoporosis, unspecified" },
  { code: "N18.9", sys: "CIE10", es: "Enfermedad renal crónica, no especificada", en: "Chronic kidney disease, unspecified" },
  { code: "N20.0", sys: "CIE10", es: "Cálculo del riñón", en: "Calculus of kidney" },
  { code: "N30.9", sys: "CIE10", es: "Cistitis, no especificada", en: "Cystitis, unspecified" },
  { code: "N39.0", sys: "CIE10", es: "Infección de vías urinarias, sitio no especificado", en: "Urinary tract infection, site not specified" },
  { code: "N40", sys: "CIE10", es: "Hiperplasia de la próstata", en: "Benign prostatic hyperplasia" },
  { code: "N76.0", sys: "CIE10", es: "Vaginitis aguda", en: "Acute vaginitis" },
  { code: "N92.6", sys: "CIE10", es: "Menstruación irregular, no especificada", en: "Irregular menstruation, unspecified" },
  { code: "O14.9", sys: "CIE10", es: "Preeclampsia, no especificada", en: "Pre-eclampsia, unspecified" },
  { code: "O21.9", sys: "CIE10", es: "Vómitos del embarazo, no especificados", en: "Vomiting of pregnancy, unspecified" },
  { code: "O26.9", sys: "CIE10", es: "Afección relacionada con el embarazo, no especificada", en: "Pregnancy related condition, unspecified" },
  { code: "O80", sys: "CIE10", es: "Parto único espontáneo", en: "Single spontaneous delivery" },
  { code: "Q21.0", sys: "CIE10", es: "Defecto del tabique ventricular", en: "Ventricular septal defect" },
  { code: "Q90.9", sys: "CIE10", es: "Síndrome de Down, no especificado", en: "Down syndrome, unspecified" },
  { code: "R05", sys: "CIE10", es: "Tos", en: "Cough" },
  { code: "R06.02", sys: "CIE10", es: "Disnea (dificultad para respirar)", en: "Shortness of breath" },
  { code: "R07.9", sys: "CIE10", es: "Dolor en el pecho, no especificado", en: "Chest pain, unspecified" },
  { code: "R10.9", sys: "CIE10", es: "Dolor abdominal, no especificado", en: "Unspecified abdominal pain" },
  { code: "R11.0", sys: "CIE10", es: "Náusea", en: "Nausea" },
  { code: "R11.10", sys: "CIE10", es: "Vómito, no especificado", en: "Vomiting, unspecified" },
  { code: "R42", sys: "CIE10", es: "Mareo y desvanecimiento", en: "Dizziness and giddiness" },
  { code: "R50.9", sys: "CIE10", es: "Fiebre, no especificada", en: "Fever, unspecified" },
  { code: "R51", sys: "CIE10", es: "Cefalea", en: "Headache" },
  { code: "R53.83", sys: "CIE10", es: "Fatiga, no especificada", en: "Other fatigue" },
  { code: "R55", sys: "CIE10", es: "Síncope y colapso", en: "Syncope and collapse" },
  { code: "S06.9", sys: "CIE10", es: "Traumatismo intracraneal, no especificado", en: "Unspecified intracranial injury" },
  { code: "S52.5", sys: "CIE10", es: "Fractura del extremo distal del radio", en: "Fracture of lower end of radius" },
  { code: "S72.0", sys: "CIE10", es: "Fractura del cuello del fémur", en: "Fracture of neck of femur" },
  { code: "S93.4", sys: "CIE10", es: "Esguince y torcedura del tobillo", en: "Sprain and strain of ankle" },
  { code: "T14.9", sys: "CIE10", es: "Traumatismo, no especificado", en: "Injury, unspecified" },
  { code: "T78.2", sys: "CIE10", es: "Choque anafiláctico, no especificado", en: "Anaphylactic shock, unspecified" },
  { code: "T78.40", sys: "CIE10", es: "Alergia, no especificada", en: "Allergy, unspecified" },
  { code: "U07.1", sys: "CIE10", es: "COVID-19", en: "COVID-19" },
  { code: "U09.9", sys: "CIE10", es: "Afección post COVID-19, no especificada", en: "Post COVID-19 condition, unspecified" },
  { code: "Z00.0", sys: "CIE10", es: "Examen médico general", en: "General medical examination" },
  { code: "Z23", sys: "CIE10", es: "Necesidad de inmunización contra enfermedad bacteriana única", en: "Need for immunization" },
  { code: "Z34.9", sys: "CIE10", es: "Supervisión de embarazo normal, no especificada", en: "Supervision of normal pregnancy, unspecified" },
  { code: "Z71.3", sys: "CIE10", es: "Consulta para asesoramiento y vigilancia dietética", en: "Dietary counseling and surveillance" },
  { code: "Z76.0", sys: "CIE10", es: "Solicitud de repetición de prescripción", en: "Encounter for issue of repeat prescription" },
  { code: "Z96.6", sys: "CIE10", es: "Presencia de implantes articulares ortopédicos", en: "Presence of orthopedic joint implants" },

  // ---- CIE-9 ----
  { code: "0.42", sys: "CIE9", es: "ENFERMEDAD POR VIRUS DE INMUNODEFICIENCIA HUMANA (HIV)", en: "ENFERMEDAD POR VIRUS DE INMUNODEFICIENCIA HUMANA (HIV)" },
  { code: "001", sys: "CIE9", es: "Cólera", en: "Cholera" },
  { code: "005.9", sys: "CIE9", es: "INTOXICACIÓN ALIMENTARIA", en: "INTOXICACIÓN ALIMENTARIA" },
  { code: "042", sys: "CIE9", es: "Infección por VIH", en: "Human immunodeficiency virus infection" },
  { code: "052.9", sys: "CIE9", es: "VARICELA", en: "VARICELA" },
  { code: "053.12", sys: "CIE9", es: "NEURALGIA POSTHERPÉTICA", en: "NEURALGIA POSTHERPÉTICA" },
  { code: "053.9", sys: "CIE9", es: "HERPES ZÓSTER", en: "HERPES ZÓSTER" },
  { code: "054.2", sys: "CIE9", es: "ESTOMATITIS HERPÉTICA", en: "ESTOMATITIS HERPÉTICA" },
  { code: "054.9", sys: "CIE9", es: "HERPES", en: "HERPES" },
  { code: "057.9", sys: "CIE9", es: "EXANTEMA VÍRICO", en: "EXANTEMA VÍRICO" },
  { code: "070.30", sys: "CIE9", es: "Hepatitis viral B aguda, sin coma hepático", en: "Acute type B viral hepatitis without hepatic coma" },
  { code: "079.99", sys: "CIE9", es: "INFECCIÓN VIRAL INESPECÍFICA", en: "INFECCIÓN VIRAL INESPECÍFICA" },
  { code: "112", sys: "CIE9", es: "CANDIDIASIS", en: "CANDIDIASIS" },
  { code: "112.0", sys: "CIE9", es: "CANDIDIASIS ORAL", en: "CANDIDIASIS ORAL" },
  { code: "117.9", sys: "CIE9", es: "OTRAS MICOSIS Y MICOSIS NO ESPECIFICADAS", en: "OTRAS MICOSIS Y MICOSIS NO ESPECIFICADAS" },
  { code: "153.9", sys: "CIE9", es: "Neoplasia maligna de colon, sin otra especificación", en: "Malignant neoplasm of colon, unspecified site" },
  { code: "162", sys: "CIE9", es: "NEOPLASIA DE TRÁQUEA / BRONQUIOS / PULMÓN", en: "NEOPLASIA DE TRÁQUEA / BRONQUIOS / PULMÓN" },
  { code: "174.9", sys: "CIE9", es: "Neoplasia maligna de mama, no especificada", en: "Malignant neoplasm of breast, unspecified" },
  { code: "191.9", sys: "CIE9", es: "NEOPLASIA MALIGNA DE CEREBRO SIN ESPECIFICAR", en: "NEOPLASIA MALIGNA DE CEREBRO SIN ESPECIFICAR" },
  { code: "199.1", sys: "CIE9", es: "NEOPLASIA SIN ESPECIFICAR", en: "NEOPLASIA SIN ESPECIFICAR" },
  { code: "239.0", sys: "CIE9", es: "NEOPLASIA DEL APARATO DIGESTIVO", en: "NEOPLASIA DEL APARATO DIGESTIVO" },
  { code: "244.9", sys: "CIE9", es: "Hipotiroidismo, no especificado", en: "Unspecified hypothyroidism" },
  { code: "250", sys: "CIE9", es: "DIABETES MELLITUS", en: "DIABETES MELLITUS" },
  { code: "250.00", sys: "CIE9", es: "Diabetes mellitus tipo 2, sin mención de complicación", en: "Diabetes mellitus without mention of complication, type II" },
  { code: "250.1", sys: "CIE9", es: "CETOACIDOSIS DIABÉTICA (SIN COMA)", en: "CETOACIDOSIS DIABÉTICA (SIN COMA)" },
  { code: "250.20", sys: "CIE9", es: "COMA HIPEROSMOLAR", en: "COMA HIPEROSMOLAR" },
  { code: "250.3", sys: "CIE9", es: "COMA HIPOGLUCÉMICO / CETOACIDÓTICO / INSULÍNICO EN DIABETES MELLITUS", en: "COMA HIPOGLUCÉMICO / CETOACIDÓTICO / INSULÍNICO EN DIABETES MELLITUS" },
  { code: "250.9", sys: "CIE9", es: "DIABETES MELLITUS CON COMPLICACIÓN NO ESPECIFICADA", en: "DIABETES MELLITUS CON COMPLICACIÓN NO ESPECIFICADA" },
  { code: "251.2", sys: "CIE9", es: "HIPOGLUCEMIA SIN COMA", en: "HIPOGLUCEMIA SIN COMA" },
  { code: "274", sys: "CIE9", es: "GOTA", en: "GOTA" },
  { code: "276.5", sys: "CIE9", es: "DESHIDRATACIÓN / HIPOVOLEMIA SIN SHOCK (POSTOPERATORIO / TRAUMÁTICO)", en: "DESHIDRATACIÓN / HIPOVOLEMIA SIN SHOCK (POSTOPERATORIO / TRAUMÁTICO)" },
  { code: "276.6", sys: "CIE9", es: "RETENCIÓN DE FLUIDOS (EXCLUYE ASCITIS / EDEMA LOCALIZADO)", en: "RETENCIÓN DE FLUIDOS (EXCLUYE ASCITIS / EDEMA LOCALIZADO)" },
  { code: "278.00", sys: "CIE9", es: "Obesidad, no especificada", en: "Obesity, unspecified" },
  { code: "285.9", sys: "CIE9", es: "ANEMIA NO ESPECIFICADA", en: "ANEMIA NO ESPECIFICADA" },
  { code: "290.0", sys: "CIE9", es: "DEMENCIA SENIL,SIN COMPLICACIONES", en: "DEMENCIA SENIL,SIN COMPLICACIONES" },
  { code: "290.3", sys: "CIE9", es: "DEMENCIA SENIL CON DELIRIO", en: "DEMENCIA SENIL CON DELIRIO" },
  { code: "291.0", sys: "CIE9", es: "DELIRIUM TREMENS Y DELIRIO ALCOHÓLICO (EXCLUYE SD DE ABSTINENCIA ALCOHÓLICA)", en: "DELIRIUM TREMENS Y DELIRIO ALCOHÓLICO (EXCLUYE SD DE ABSTINENCIA ALCOHÓLICA)" },
  { code: "291.81", sys: "CIE9", es: "SÍNDROME DE ABSTINENCIA ALCOHÓLICA (EXCLUYE D.TREMENS / DELIRIO ALCOHÓLICO)", en: "SÍNDROME DE ABSTINENCIA ALCOHÓLICA (EXCLUYE D.TREMENS / DELIRIO ALCOHÓLICO)" },
  { code: "291.9", sys: "CIE9", es: "PSICOSIS ALCOHÓLICA", en: "PSICOSIS ALCOHÓLICA" },
  { code: "292.0", sys: "CIE9", es: "SÍNDROME DE ABSTINENCIA A DROGAS / PSICOTROPOS", en: "SÍNDROME DE ABSTINENCIA A DROGAS / PSICOTROPOS" },
  { code: "293.0", sys: "CIE9", es: "SÍNDROME CONFUSIONAL AGUDO", en: "SÍNDROME CONFUSIONAL AGUDO" },
  { code: "295.9", sys: "CIE9", es: "ESQUIZOFRENIA / PSICOSIS ESQUIZOFRÉNICA", en: "ESQUIZOFRENIA / PSICOSIS ESQUIZOFRÉNICA" },
  { code: "296.2", sys: "CIE9", es: "DEPRESIÓN PSICÓTICA / ENDÓGENA / MONOPOLAR", en: "DEPRESIÓN PSICÓTICA / ENDÓGENA / MONOPOLAR" },
  { code: "296.20", sys: "CIE9", es: "Trastorno depresivo mayor, episodio único", en: "Major depressive disorder, single episode, unspecified" },
  { code: "296.6", sys: "CIE9", es: "TRASTORNO AFECTIVO BIPOLAR / PSICOSIS MANÍACO-DEPRESIVA", en: "TRASTORNO AFECTIVO BIPOLAR / PSICOSIS MANÍACO-DEPRESIVA" },
  { code: "297.9", sys: "CIE9", es: "ESTADO PARANOIDE", en: "ESTADO PARANOIDE" },
  { code: "298.9", sys: "CIE9", es: "PSICOSIS SIN ESPECIFICAR", en: "PSICOSIS SIN ESPECIFICAR" },
  { code: "300", sys: "CIE9", es: "TRASTORNOS NEURÓTICOS", en: "TRASTORNOS NEURÓTICOS" },
  { code: "300.00", sys: "CIE9", es: "Estado de ansiedad, no especificado", en: "Anxiety state, unspecified" },
  { code: "300.10", sys: "CIE9", es: "HISTERIA", en: "HISTERIA" },
  { code: "300.4", sys: "CIE9", es: "DEPRESIÓN NEURÓTICA", en: "DEPRESIÓN NEURÓTICA" },
  { code: "300.9", sys: "CIE9", es: "INTENTO DE SUICIDIO", en: "INTENTO DE SUICIDIO" },
  { code: "303.0", sys: "CIE9", es: "INTOXICACIÓN ALCOHÓLICA AGUDA EN ALCOHOLISMO", en: "INTOXICACIÓN ALCOHÓLICA AGUDA EN ALCOHOLISMO" },
  { code: "305", sys: "CIE9", es: "ABUSO DE DROGAS SIN DEPENDENCIA", en: "ABUSO DE DROGAS SIN DEPENDENCIA" },
  { code: "305.0", sys: "CIE9", es: "ABUSO DE ALCOHOL/EMBRIAGUEZ (EXCLUYE INTOXICA_OL/PSICOSIS_OL/DELI_OL)", en: "ABUSO DE ALCOHOL/EMBRIAGUEZ (EXCLUYE INTOXICA_OL/PSICOSIS_OL/DELI_OL)" },
  { code: "306.4", sys: "CIE9", es: "AEROFAGIA", en: "AEROFAGIA" },
  { code: "307.1", sys: "CIE9", es: "ANOREXIA NERVIOSA", en: "ANOREXIA NERVIOSA" },
  { code: "307.80", sys: "CIE9", es: "DOLOR PSICÓGENO", en: "DOLOR PSICÓGENO" },
  { code: "307.81", sys: "CIE9", es: "CEFALEA TENSIONAL (EXCLUYE MIGRAÑA)", en: "CEFALEA TENSIONAL (EXCLUYE MIGRAÑA)" },
  { code: "308", sys: "CIE9", es: "REACCIÓN AGUDA STRESS", en: "REACCIÓN AGUDA STRESS" },
  { code: "309.29", sys: "CIE9", es: "CRISIS EMOCIONAL", en: "CRISIS EMOCIONAL" },
  { code: "312.9", sys: "CIE9", es: "PERTURBACIÓN NO ESPECIFICADA DEL COMPORTAMIENTO", en: "PERTURBACIÓN NO ESPECIFICADA DEL COMPORTAMIENTO" },
  { code: "331.0", sys: "CIE9", es: "ALZHEIMER", en: "ALZHEIMER" },
  { code: "332", sys: "CIE9", es: "PARKINSON", en: "PARKINSON" },
  { code: "337.2", sys: "CIE9", es: "SíNCOPE DE SENO CAROTIDEO", en: "SíNCOPE DE SENO CAROTIDEO" },
  { code: "342", sys: "CIE9", es: "HEMIPLEJIA Y HEMIPARESIA", en: "HEMIPLEJIA Y HEMIPARESIA" },
  { code: "342.9", sys: "CIE9", es: "HEMIPLEJIA SIN ESPECIFICAR", en: "HEMIPLEJIA SIN ESPECIFICAR" },
  { code: "344.9", sys: "CIE9", es: "PARÁLISIS NO ESPECIFICADA", en: "PARÁLISIS NO ESPECIFICADA" },
  { code: "345.9", sys: "CIE9", es: "EPILEPSIA NO ESPECIFICADA", en: "EPILEPSIA NO ESPECIFICADA" },
  { code: "345.90", sys: "CIE9", es: "Epilepsia, no especificada, sin mención de intratabilidad", en: "Epilepsy, unspecified, without mention of intractable epilepsy" },
  { code: "346.9", sys: "CIE9", es: "MIGRAÑA", en: "MIGRAÑA" },
  { code: "346.90", sys: "CIE9", es: "Migraña, no especificada", en: "Migraine, unspecified" },
  { code: "350.1", sys: "CIE9", es: "NEURALGIA DEL TRIGÉMINO (EXCLUYE POSTHERPÉTICA)", en: "NEURALGIA DEL TRIGÉMINO (EXCLUYE POSTHERPÉTICA)" },
  { code: "369.70", sys: "CIE9", es: "DETERIORO OCULAR SIN ESPECIFICAR", en: "DETERIORO OCULAR SIN ESPECIFICAR" },
  { code: "372.0", sys: "CIE9", es: "CONJUNTIVITIS AGUDA", en: "CONJUNTIVITIS AGUDA" },
  { code: "372.72", sys: "CIE9", es: "HEMORRAGIA CONJUNTIVAL", en: "HEMORRAGIA CONJUNTIVAL" },
  { code: "373", sys: "CIE9", es: "INFLAMACIÓN DE LOS PÁRPADOS (BLEFARITIS / ORZUELO / CHALAZIÓN / DERMATITIS)", en: "INFLAMACIÓN DE LOS PÁRPADOS (BLEFARITIS / ORZUELO / CHALAZIÓN / DERMATITIS)" },
  { code: "382.0", sys: "CIE9", es: "OTITIS MEDIA AGUDA", en: "OTITIS MEDIA AGUDA" },
  { code: "382.3", sys: "CIE9", es: "OTITIS MEDIA CRÓNICA SUPURATIVA", en: "OTITIS MEDIA CRÓNICA SUPURATIVA" },
  { code: "382.9", sys: "CIE9", es: "OTITIS MEDIA NO ESPECIFICADA", en: "OTITIS MEDIA NO ESPECIFICADA" },
  { code: "386.10", sys: "CIE9", es: "VÉRTIGO PERIFÉRICO NO ESPECIFICADO", en: "VÉRTIGO PERIFÉRICO NO ESPECIFICADO" },
  { code: "386.11", sys: "CIE9", es: "VÉRTIGO POSICIONAL PAROXÍSTICO BENIGNO", en: "VÉRTIGO POSICIONAL PAROXÍSTICO BENIGNO" },
  { code: "386.2", sys: "CIE9", es: "VÉRTIGO CENTRAL", en: "VÉRTIGO CENTRAL" },
  { code: "386.9", sys: "CIE9", es: "SÍNDROME VERTIGINOSO Y LABERÍNTICO SIN ESPECIFICAR", en: "SÍNDROME VERTIGINOSO Y LABERÍNTICO SIN ESPECIFICAR" },
  { code: "388.3", sys: "CIE9", es: "ACÚFENO (TÍNNITUS / RUIDO OÍDOS)", en: "ACÚFENO (TÍNNITUS / RUIDO OÍDOS)" },
  { code: "388.6", sys: "CIE9", es: "OTORREA", en: "OTORREA" },
  { code: "388.69", sys: "CIE9", es: "OTORRAGIA", en: "OTORRAGIA" },
  { code: "388.7", sys: "CIE9", es: "OTALGIA", en: "OTALGIA" },
  { code: "401", sys: "CIE9", es: "TENSIÓN ARTERIAL ALTA", en: "TENSIÓN ARTERIAL ALTA" },
  { code: "401.9", sys: "CIE9", es: "Hipertensión esencial, no especificada", en: "Unspecified essential hypertension" },
  { code: "402", sys: "CIE9", es: "HTA CON REPERCUSIÓN HEMODINÁMICA", en: "HTA CON REPERCUSIÓN HEMODINÁMICA" },
  { code: "405", sys: "CIE9", es: "HTA SECUNDARIA", en: "HTA SECUNDARIA" },
  { code: "410.0", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO ANTEROLATERAL", en: "INFARTO AGUDO DE MIOCARDIO ANTEROLATERAL" },
  { code: "410.1", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO ANTERIOR", en: "INFARTO AGUDO DE MIOCARDIO ANTERIOR" },
  { code: "410.2", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO INFEROLATERAL", en: "INFARTO AGUDO DE MIOCARDIO INFEROLATERAL" },
  { code: "410.3", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO INFEROPOSTERIOR", en: "INFARTO AGUDO DE MIOCARDIO INFEROPOSTERIOR" },
  { code: "410.4", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO INFERIOR", en: "INFARTO AGUDO DE MIOCARDIO INFERIOR" },
  { code: "410.5", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO LATERAL", en: "INFARTO AGUDO DE MIOCARDIO LATERAL" },
  { code: "410.6", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO POSTERIOR", en: "INFARTO AGUDO DE MIOCARDIO POSTERIOR" },
  { code: "410.7", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO SUBENDOCÁRDICO", en: "INFARTO AGUDO DE MIOCARDIO SUBENDOCÁRDICO" },
  { code: "410.9", sys: "CIE9", es: "INFARTO AGUDO DE MIOCARDIO SIN ESPECIFICAR", en: "INFARTO AGUDO DE MIOCARDIO SIN ESPECIFICAR" },
  { code: "410.90", sys: "CIE9", es: "Infarto agudo de miocardio, no especificado", en: "Acute myocardial infarction, unspecified site, episode of care unspecified" },
  { code: "411.0", sys: "CIE9", es: "ANGOR POSTINFARTO", en: "ANGOR POSTINFARTO" },
  { code: "411.1", sys: "CIE9", es: "ANGOR DE INICIO", en: "ANGOR DE INICIO" },
  { code: "413.0", sys: "CIE9", es: "ANGINA DE DECÚBITO (NOCTURNA)", en: "ANGINA DE DECÚBITO (NOCTURNA)" },
  { code: "413.1", sys: "CIE9", es: "ANGINA DE PRINZMETAL", en: "ANGINA DE PRINZMETAL" },
  { code: "413.9", sys: "CIE9", es: "ANGINA DE PECHO NO ESPECIFICADA", en: "ANGINA DE PECHO NO ESPECIFICADA" },
  { code: "414.1", sys: "CIE9", es: "ANEURISMA CARDIACO", en: "ANEURISMA CARDIACO" },
  { code: "414.9", sys: "CIE9", es: "CARDIOPATÍA ISQUÉMICA CRÓNICA NO ESPECIFICADA", en: "CARDIOPATÍA ISQUÉMICA CRÓNICA NO ESPECIFICADA" },
  { code: "415.0", sys: "CIE9", es: "COR PULMONALE AGUDO", en: "COR PULMONALE AGUDO" },
  { code: "415.1", sys: "CIE9", es: "TROMBOEMBOLISMO PULMONAR", en: "TROMBOEMBOLISMO PULMONAR" },
  { code: "420", sys: "CIE9", es: "PERICARDITIS AGUDA", en: "PERICARDITIS AGUDA" },
  { code: "422", sys: "CIE9", es: "MIOCARDITIS", en: "MIOCARDITIS" },
  { code: "423.9", sys: "CIE9", es: "TAPONAMIENTO CARDIACO", en: "TAPONAMIENTO CARDIACO" },
  { code: "426.0", sys: "CIE9", es: "BLOQUEO AV COMPLETO", en: "BLOQUEO AV COMPLETO" },
  { code: "426.11", sys: "CIE9", es: "BLOQUEO AV PRIMER GRADO", en: "BLOQUEO AV PRIMER GRADO" },
  { code: "426.12", sys: "CIE9", es: "BLOQUEO AV SEGUNDO GRADO TIPO II", en: "BLOQUEO AV SEGUNDO GRADO TIPO II" },
  { code: "426.13", sys: "CIE9", es: "BLOQUEO AV SEGUNDO GRADO TIPO I / WENCKEBACH", en: "BLOQUEO AV SEGUNDO GRADO TIPO I / WENCKEBACH" },
  { code: "426.2", sys: "CIE9", es: "HEMIBLOQUEO DE RAMA IZQUIERDA", en: "HEMIBLOQUEO DE RAMA IZQUIERDA" },
  { code: "426.4", sys: "CIE9", es: "BLOQUEO DE LA RAMA DERECHA", en: "BLOQUEO DE LA RAMA DERECHA" },
  { code: "426.9", sys: "CIE9", es: "ALTERACIÓN CONDUCCIÓN CARDIACA", en: "ALTERACIÓN CONDUCCIÓN CARDIACA" },
  { code: "427.0", sys: "CIE9", es: "TAQUICARDIA PAROXÍSTICA SUPRAVENTRICULAR", en: "TAQUICARDIA PAROXÍSTICA SUPRAVENTRICULAR" },
  { code: "427.1", sys: "CIE9", es: "TAQUICARDIA VENTRICULAR PAROXÍSTICA", en: "TAQUICARDIA VENTRICULAR PAROXÍSTICA" },
  { code: "427.2", sys: "CIE9", es: "TAQUICARDIA PAROXÍSTICA NO ESPECIFICADA", en: "TAQUICARDIA PAROXÍSTICA NO ESPECIFICADA" },
  { code: "427.31", sys: "CIE9", es: "FIBRILACIÓN AURICULAR", en: "FIBRILACIÓN AURICULAR" },
  { code: "427.32", sys: "CIE9", es: "FLUTER AURICULAR", en: "FLUTER AURICULAR" },
  { code: "427.41", sys: "CIE9", es: "FIBRILACIÓN VENTRICULAR", en: "FIBRILACIÓN VENTRICULAR" },
  { code: "427.42", sys: "CIE9", es: "FLUTER VENTRICULAR", en: "FLUTER VENTRICULAR" },
  { code: "427.5", sys: "CIE9", es: "PARO CARDIACO / CARDIORESPIRATORIO", en: "PARO CARDIACO / CARDIORESPIRATORIO" },
  { code: "427.6", sys: "CIE9", es: "EXTRASÍSTOLES", en: "EXTRASÍSTOLES" },
  { code: "427.81", sys: "CIE9", es: "BRADICARDIA", en: "BRADICARDIA" },
  { code: "427.89", sys: "CIE9", es: "TAQUICARDIA SINUSAL", en: "TAQUICARDIA SINUSAL" },
  { code: "427.9", sys: "CIE9", es: "ARRITMIA CARDIACA SIN ESPECIFICAR", en: "ARRITMIA CARDIACA SIN ESPECIFICAR" },
  { code: "428.0", sys: "CIE9", es: "Insuficiencia cardíaca congestiva, no especificada", en: "Congestive heart failure, unspecified" },
  { code: "428.1", sys: "CIE9", es: "INSUFICIENCIA CARDIACA IZQUIERDA", en: "INSUFICIENCIA CARDIACA IZQUIERDA" },
  { code: "428.9", sys: "CIE9", es: "INSUFICIENCIA CARDIACA (FALLO CARDIACO NO ESPECIFICADO)", en: "INSUFICIENCIA CARDIACA (FALLO CARDIACO NO ESPECIFICADO)" },
  { code: "430", sys: "CIE9", es: "HEMORRAGIA SUBARACNOIDEA NO TRAUMÁTICA", en: "HEMORRAGIA SUBARACNOIDEA NO TRAUMÁTICA" },
  { code: "431", sys: "CIE9", es: "HEMORRAGIA CEREBRAL", en: "HEMORRAGIA CEREBRAL" },
  { code: "432.0", sys: "CIE9", es: "HEMATOMA EPIDURAL NO TRAUMÁTICO", en: "HEMATOMA EPIDURAL NO TRAUMÁTICO" },
  { code: "432.1", sys: "CIE9", es: "HEMATOMA SUBDURAL NO TRAUMÁTICO", en: "HEMATOMA SUBDURAL NO TRAUMÁTICO" },
  { code: "435.9", sys: "CIE9", es: "ACCIDENTE CEREBRAVASCULAR AGUDO EN EVOLUCIÓN / TIA", en: "ACCIDENTE CEREBRAVASCULAR AGUDO EN EVOLUCIÓN / TIA" },
  { code: "436", sys: "CIE9", es: "ACCIDENTE CEREBROVASCULAR AGUDO ESTABLECIDO", en: "ACCIDENTE CEREBROVASCULAR AGUDO ESTABLECIDO" },
  { code: "437.2", sys: "CIE9", es: "ENCEFALOPATÍA HIPERTENSIVA", en: "ENCEFALOPATÍA HIPERTENSIVA" },
  { code: "437.9", sys: "CIE9", es: "INSUFICIENCIA CEREBRO-VASCULAR INESPECÍFICA", en: "INSUFICIENCIA CEREBRO-VASCULAR INESPECÍFICA" },
  { code: "441.0", sys: "CIE9", es: "DISECCIÓN AÓRTICA / ANEURISMA DISECANTE AORTA ROTO", en: "DISECCIÓN AÓRTICA / ANEURISMA DISECANTE AORTA ROTO" },
  { code: "441.2", sys: "CIE9", es: "ANEURISMA AORTA TORÁCICO", en: "ANEURISMA AORTA TORÁCICO" },
  { code: "441.4", sys: "CIE9", es: "ANEURISMA AORTA TORACOABDOMINAL", en: "ANEURISMA AORTA TORACOABDOMINAL" },
  { code: "441.9", sys: "CIE9", es: "ANEURISMA AORTA SIN ESPECIFICAR", en: "ANEURISMA AORTA SIN ESPECIFICAR" },
  { code: "444.21", sys: "CIE9", es: "ISQUEMIA DE EXTREMIDADES SUPERIORES", en: "ISQUEMIA DE EXTREMIDADES SUPERIORES" },
  { code: "444.22", sys: "CIE9", es: "ISQUEMIA DE EXTREMIDADES INFERIORES", en: "ISQUEMIA DE EXTREMIDADES INFERIORES" },
  { code: "451.0", sys: "CIE9", es: "TROMBOSIS VENOSA SUPERFICIAL MIEMBRO INFERIOR", en: "TROMBOSIS VENOSA SUPERFICIAL MIEMBRO INFERIOR" },
  { code: "451.1", sys: "CIE9", es: "TROMBOSIS VENOSA PROFUNDA MIEMBRO INFERIOR", en: "TROMBOSIS VENOSA PROFUNDA MIEMBRO INFERIOR" },
  { code: "451.82", sys: "CIE9", es: "TROMBOSIS VENOSA SUPERFICIAL MIEMBRO SUPERIOR", en: "TROMBOSIS VENOSA SUPERFICIAL MIEMBRO SUPERIOR" },
  { code: "451.83", sys: "CIE9", es: "TROMBOSIS VENOSA PROFUNDA MIEMBRO SUPERIOR", en: "TROMBOSIS VENOSA PROFUNDA MIEMBRO SUPERIOR" },
  { code: "451.9", sys: "CIE9", es: "FLEBITIS INESPECÍFICA", en: "FLEBITIS INESPECÍFICA" },
  { code: "453.1", sys: "CIE9", es: "FLEBITIS MIGRATORIA", en: "FLEBITIS MIGRATORIA" },
  { code: "454.1", sys: "CIE9", es: "VARICOFLEBITIS", en: "VARICOFLEBITIS" },
  { code: "454.9", sys: "CIE9", es: "VARICORRAGIA", en: "VARICORRAGIA" },
  { code: "455", sys: "CIE9", es: "HEMORROIDES", en: "HEMORROIDES" },
  { code: "458.0", sys: "CIE9", es: "HIPOTENSIÓN ORTOSTÁTICA", en: "HIPOTENSIÓN ORTOSTÁTICA" },
  { code: "458.9", sys: "CIE9", es: "HIPOTENSIÓN NO ESPECIFICADA", en: "HIPOTENSIÓN NO ESPECIFICADA" },
  { code: "459.81", sys: "CIE9", es: "INSUFICIENCIA VENOSA PERIFÉRICA INESPECÍFICA", en: "INSUFICIENCIA VENOSA PERIFÉRICA INESPECÍFICA" },
  { code: "459.9", sys: "CIE9", es: "TRASTORNO DEL APARATO CIRCULATORIO NO ESPECIFICADO", en: "TRASTORNO DEL APARATO CIRCULATORIO NO ESPECIFICADO" },
  { code: "460", sys: "CIE9", es: "Resfriado común", en: "Common cold" },
  { code: "461", sys: "CIE9", es: "SINUSITIS AGUDA", en: "SINUSITIS AGUDA" },
  { code: "462", sys: "CIE9", es: "FARINGITIS AGUDA", en: "FARINGITIS AGUDA" },
  { code: "463", sys: "CIE9", es: "AMIGDALITIS AGUDA", en: "AMIGDALITIS AGUDA" },
  { code: "464", sys: "CIE9", es: "LARINGITIS AGUDA (EXCLUYE LAS ASOCIADAS A LA GRIPE / ESTREPTOCOCOS)", en: "LARINGITIS AGUDA (EXCLUYE LAS ASOCIADAS A LA GRIPE / ESTREPTOCOCOS)" },
  { code: "464.10", sys: "CIE9", es: "TRAQUEÍTIS AGUDA SIN OBSTRUCCIÓN", en: "TRAQUEÍTIS AGUDA SIN OBSTRUCCIÓN" },
  { code: "464.11", sys: "CIE9", es: "TRAQUEÍTIS AGUDA CON OBSTRUCCIÓN", en: "TRAQUEÍTIS AGUDA CON OBSTRUCCIÓN" },
  { code: "464.30", sys: "CIE9", es: "EPIGLOTITIS SIN OBSTRUCCIÓN", en: "EPIGLOTITIS SIN OBSTRUCCIÓN" },
  { code: "464.31", sys: "CIE9", es: "EPIGLOTITIS CON OBSTRUCCIÓN", en: "EPIGLOTITIS CON OBSTRUCCIÓN" },
  { code: "464.4", sys: "CIE9", es: "CRUP", en: "CRUP" },
  { code: "465.8", sys: "CIE9", es: "FARINGOAMIGDALITIS", en: "FARINGOAMIGDALITIS" },
  { code: "465.9", sys: "CIE9", es: "INFECCIÓN RESPIRATORIA AGUDA (EXCLUYE LAS ASOCIADAS A LA GRIPE / ESTREPTOCOCOS)", en: "INFECCIÓN RESPIRATORIA AGUDA (EXCLUYE LAS ASOCIADAS A LA GRIPE / ESTREPTOCOCOS)" },
  { code: "466.0", sys: "CIE9", es: "BRONQUITIS AGUDA", en: "BRONQUITIS AGUDA" },
  { code: "472.0", sys: "CIE9", es: "RINITIS CRÓNICA", en: "RINITIS CRÓNICA" },
  { code: "472.1", sys: "CIE9", es: "FARINGITIS CRÓNICA", en: "FARINGITIS CRÓNICA" },
  { code: "473", sys: "CIE9", es: "SINUSITIS CRÓNICA", en: "SINUSITIS CRÓNICA" },
  { code: "478.6", sys: "CIE9", es: "EDEMA DE LARINGE (GLOTIS / SUBGLÓTICO / SUPRAGLÓTICO)", en: "EDEMA DE LARINGE (GLOTIS / SUBGLÓTICO / SUPRAGLÓTICO)" },
  { code: "478.75", sys: "CIE9", es: "ESPASMO LARÍNGEO", en: "ESPASMO LARÍNGEO" },
  { code: "485", sys: "CIE9", es: "BRONCONEUMONÍA", en: "BRONCONEUMONÍA" },
  { code: "486", sys: "CIE9", es: "Neumonía, organismo no especificado", en: "Pneumonia, organism unspecified" },
  { code: "487", sys: "CIE9", es: "GRIPE", en: "GRIPE" },
  { code: "490", sys: "CIE9", es: "BRONQUITIS", en: "BRONQUITIS" },
  { code: "491.21", sys: "CIE9", es: "EPOC REAGUDIZADO", en: "EPOC REAGUDIZADO" },
  { code: "491.9", sys: "CIE9", es: "BRONQUITIS CRÓNICA NO ESPECIFICADA", en: "BRONQUITIS CRÓNICA NO ESPECIFICADA" },
  { code: "492", sys: "CIE9", es: "ENFISEMA PULMONAR", en: "ENFISEMA PULMONAR" },
  { code: "493.9", sys: "CIE9", es: "ASMA NO ESPECIFICADA (BRONQUITIS ASMATICA)", en: "ASMA NO ESPECIFICADA (BRONQUITIS ASMATICA)" },
  { code: "493.90", sys: "CIE9", es: "Asma, no especificada", en: "Asthma, unspecified" },
  { code: "493.91", sys: "CIE9", es: "STATUS ASMÁTICO", en: "STATUS ASMÁTICO" },
  { code: "511.0", sys: "CIE9", es: "PLEURITIS", en: "PLEURITIS" },
  { code: "511.8", sys: "CIE9", es: "HEMOTÓRAX", en: "HEMOTÓRAX" },
  { code: "512.0", sys: "CIE9", es: "NEUMOTÓRAX ESPONTÁNEO POR TENSIÓN", en: "NEUMOTÓRAX ESPONTÁNEO POR TENSIÓN" },
  { code: "512.8", sys: "CIE9", es: "NEUMOTÓRAX ESPONTÁNEO", en: "NEUMOTÓRAX ESPONTÁNEO" },
  { code: "515", sys: "CIE9", es: "FIBROSIS PULMONAR", en: "FIBROSIS PULMONAR" },
  { code: "518.4", sys: "CIE9", es: "EDEMA AGUDO DE PULMÓN NO ESPECIFICADO", en: "EDEMA AGUDO DE PULMÓN NO ESPECIFICADO" },
  { code: "518.82", sys: "CIE9", es: "DISTRÉSS RESPIRATORIO ADULTO / INSUFICIENCIA RESPIRATORIA AGUDA", en: "DISTRÉSS RESPIRATORIO ADULTO / INSUFICIENCIA RESPIRATORIA AGUDA" },
  { code: "519.1", sys: "CIE9", es: "BRONCOESPASMO", en: "BRONCOESPASMO" },
  { code: "519.8", sys: "CIE9", es: "OBSTRUCCIÓN VÍA AÉREA", en: "OBSTRUCCIÓN VÍA AÉREA" },
  { code: "522.7", sys: "CIE9", es: "FLEMÓN DENTARIO", en: "FLEMÓN DENTARIO" },
  { code: "523.0", sys: "CIE9", es: "GINGIVITIS AGUDA", en: "GINGIVITIS AGUDA" },
  { code: "524.62", sys: "CIE9", es: "DOLOR TEMPORO-MANDIBULAR", en: "DOLOR TEMPORO-MANDIBULAR" },
  { code: "525.9", sys: "CIE9", es: "ODONTALGIA", en: "ODONTALGIA" },
  { code: "527.2", sys: "CIE9", es: "SIALOADENITIS / PAROTIDITIS", en: "SIALOADENITIS / PAROTIDITIS" },
  { code: "528.2", sys: "CIE9", es: "AFTAS BUCALES (EXCLUYE ESTOMATITIS HERPÉTICA)", en: "AFTAS BUCALES (EXCLUYE ESTOMATITIS HERPÉTICA)" },
  { code: "530.81", sys: "CIE9", es: "REFLUJO GASTROESOFÁGICO", en: "REFLUJO GASTROESOFÁGICO" },
  { code: "533.90", sys: "CIE9", es: "Úlcera péptica de sitio no especificado", en: "Peptic ulcer of unspecified site, unspecified" },
  { code: "534.9", sys: "CIE9", es: "CRISIS ULCEROSA GASTROYEYUNAL", en: "CRISIS ULCEROSA GASTROYEYUNAL" },
  { code: "535.0", sys: "CIE9", es: "GASTRITIS AGUDA", en: "GASTRITIS AGUDA" },
  { code: "536.8", sys: "CIE9", es: "DISPEPSIA", en: "DISPEPSIA" },
  { code: "540.9", sys: "CIE9", es: "Apendicitis aguda, sin mención de peritonitis", en: "Acute appendicitis without mention of peritonitis" },
  { code: "541", sys: "CIE9", es: "APENDICITIS", en: "APENDICITIS" },
  { code: "550.90", sys: "CIE9", es: "HERNIA INGUINAL", en: "HERNIA INGUINAL" },
  { code: "553", sys: "CIE9", es: "HERNIA ABDOMINAL", en: "HERNIA ABDOMINAL" },
  { code: "553.1", sys: "CIE9", es: "HERNIA UMBILICAL", en: "HERNIA UMBILICAL" },
  { code: "553.20", sys: "CIE9", es: "EVENTRACIÓN (HERNIA VENTRAL)", en: "EVENTRACIÓN (HERNIA VENTRAL)" },
  { code: "553.3", sys: "CIE9", es: "HERNIA DE HIATO", en: "HERNIA DE HIATO" },
  { code: "558.9", sys: "CIE9", es: "GASTROENTERITIS / ENTERITIS AGUDA", en: "GASTROENTERITIS / ENTERITIS AGUDA" },
  { code: "560.39", sys: "CIE9", es: "OBSTRUCCIÓN INTESTINAL CON IMPACTACIÓN / FECALOMA", en: "OBSTRUCCIÓN INTESTINAL CON IMPACTACIÓN / FECALOMA" },
  { code: "564.0", sys: "CIE9", es: "ESTREÑIMIENTO", en: "ESTREÑIMIENTO" },
  { code: "564.1", sys: "CIE9", es: "COLON IRRITABLE", en: "COLON IRRITABLE" },
  { code: "565.0", sys: "CIE9", es: "FISURA ANAL", en: "FISURA ANAL" },
  { code: "566", sys: "CIE9", es: "ABSCESO PERIANAL / PERIRRECTAL", en: "ABSCESO PERIANAL / PERIRRECTAL" },
  { code: "569.1", sys: "CIE9", es: "PROLAPSO DE RECTO", en: "PROLAPSO DE RECTO" },
  { code: "569.3", sys: "CIE9", es: "RECTORRAGIA", en: "RECTORRAGIA" },
  { code: "569.42", sys: "CIE9", es: "DOLOR DE ANO", en: "DOLOR DE ANO" },
  { code: "571.2", sys: "CIE9", es: "CIRROSIS HEPÁTICA ALCOHÓLICA", en: "CIRROSIS HEPÁTICA ALCOHÓLICA" },
  { code: "571.5", sys: "CIE9", es: "CIRROSIS HEPÁTICA NO ALCOHÓLICA", en: "CIRROSIS HEPÁTICA NO ALCOHÓLICA" },
  { code: "574.2", sys: "CIE9", es: "CÓLICO HEPÁTICO", en: "CÓLICO HEPÁTICO" },
  { code: "574.21", sys: "CIE9", es: "CÓLICO BILIAR", en: "CÓLICO BILIAR" },
  { code: "575.0", sys: "CIE9", es: "COLECISTITIS AGUDA", en: "COLECISTITIS AGUDA" },
  { code: "576.1", sys: "CIE9", es: "COLANGITIS", en: "COLANGITIS" },
  { code: "578.0", sys: "CIE9", es: "HEMATEMESIS", en: "HEMATEMESIS" },
  { code: "578.1", sys: "CIE9", es: "MELENAS", en: "MELENAS" },
  { code: "578.9", sys: "CIE9", es: "HEMORRAGIA DIGESTIVA ALTA / BAJA NO ESPECIFICADA", en: "HEMORRAGIA DIGESTIVA ALTA / BAJA NO ESPECIFICADA" },
  { code: "590.0", sys: "CIE9", es: "PIELONEFRITIS CRÓNICA", en: "PIELONEFRITIS CRÓNICA" },
  { code: "590.1", sys: "CIE9", es: "PIELONEFRITIS AGUDA", en: "PIELONEFRITIS AGUDA" },
  { code: "593.81", sys: "CIE9", es: "TRASTORNOS VASCULARES DE RIÑÓN", en: "TRASTORNOS VASCULARES DE RIÑÓN" },
  { code: "595.9", sys: "CIE9", es: "CISTITIS", en: "CISTITIS" },
  { code: "597.80", sys: "CIE9", es: "URETRITIS", en: "URETRITIS" },
  { code: "599.0", sys: "CIE9", es: "Infección de vías urinarias, sitio no especificado", en: "Urinary tract infection, site not specified" },
  { code: "599.7", sys: "CIE9", es: "HEMATURIA", en: "HEMATURIA" },
  { code: "599.89", sys: "CIE9", es: "HEMORRAGIA TRACTO GENITOURINARIO", en: "HEMORRAGIA TRACTO GENITOURINARIO" },
  { code: "600", sys: "CIE9", es: "HIPERPLASIA PROSTÁTICA / PROSTATISMO", en: "HIPERPLASIA PROSTÁTICA / PROSTATISMO" },
  { code: "601.9", sys: "CIE9", es: "PROSTATITIS NO ESPECIFICADA", en: "PROSTATITIS NO ESPECIFICADA" },
  { code: "604", sys: "CIE9", es: "ORQUITIS / EPIDIDIMITIS", en: "ORQUITIS / EPIDIDIMITIS" },
  { code: "607.8", sys: "CIE9", es: "PRIAPISMO", en: "PRIAPISMO" },
  { code: "608.86", sys: "CIE9", es: "EDEMA GENITALES MASCULINOS", en: "EDEMA GENITALES MASCULINOS" },
  { code: "611.0", sys: "CIE9", es: "MASTITIS (NO EN LACTANCIA)", en: "MASTITIS (NO EN LACTANCIA)" },
  { code: "611.9", sys: "CIE9", es: "TRASTORNOS MAMARIOS", en: "TRASTORNOS MAMARIOS" },
  { code: "618.0", sys: "CIE9", es: "PROLAPSO VAGINAL", en: "PROLAPSO VAGINAL" },
  { code: "618.1", sys: "CIE9", es: "PROLAPSO UTERINO", en: "PROLAPSO UTERINO" },
  { code: "625.3", sys: "CIE9", es: "DISMENORREA", en: "DISMENORREA" },
  { code: "626.6", sys: "CIE9", es: "METRORRAGIA", en: "METRORRAGIA" },
  { code: "629.8", sys: "CIE9", es: "EDEMA GENITALES FEMENINOS", en: "EDEMA GENITALES FEMENINOS" },
  { code: "633.9", sys: "CIE9", es: "EMBARAZO ECTÓPICO NO ESPECIFICADO", en: "EMBARAZO ECTÓPICO NO ESPECIFICADO" },
  { code: "637.90", sys: "CIE9", es: "ABORTO CONSUMADO", en: "ABORTO CONSUMADO" },
  { code: "640.00", sys: "CIE9", es: "ABORTO (AMENAZA)", en: "ABORTO (AMENAZA)" },
  { code: "640.90", sys: "CIE9", es: "HEMORRAGIA PRIMER TRIMESTRE (= < 22 SEMANAS)", en: "HEMORRAGIA PRIMER TRIMESTRE (= < 22 SEMANAS)" },
  { code: "641.90", sys: "CIE9", es: "HEMORRAGIA TERCER TRIMESTRE (> 22 SEMANAS)", en: "HEMORRAGIA TERCER TRIMESTRE (> 22 SEMANAS)" },
  { code: "642.40", sys: "CIE9", es: "PREECLAMPSIA LEVE O NO ESPECIFICADA", en: "PREECLAMPSIA LEVE O NO ESPECIFICADA" },
  { code: "642.50", sys: "CIE9", es: "PREECLAMPSIA GRAVE", en: "PREECLAMPSIA GRAVE" },
  { code: "642.60", sys: "CIE9", es: "ECLAMPSIA", en: "ECLAMPSIA" },
  { code: "643.90", sys: "CIE9", es: "VÓMITOS / NAÚSEAS DEL EMBARAZO", en: "VÓMITOS / NAÚSEAS DEL EMBARAZO" },
  { code: "644.10", sys: "CIE9", es: "AMENAZA DE PARTO / PRÓDROMOS", en: "AMENAZA DE PARTO / PRÓDROMOS" },
  { code: "644.11", sys: "CIE9", es: "PARTO EN CURSO", en: "PARTO EN CURSO" },
  { code: "644.21", sys: "CIE9", es: "PARTO PREMATURO", en: "PARTO PREMATURO" },
  { code: "650", sys: "CIE9", es: "PARTO NORMAL SIN COMPLICACIONES", en: "PARTO NORMAL SIN COMPLICACIONES" },
  { code: "669.9", sys: "CIE9", es: "PARTO COMPLICADO", en: "PARTO COMPLICADO" },
  { code: "676.9", sys: "CIE9", es: "MASTITIS / TRASTORNOS MAMARIOS (EN LACTANCIA)", en: "MASTITIS / TRASTORNOS MAMARIOS (EN LACTANCIA)" },
  { code: "682.9", sys: "CIE9", es: "ABSCESO / CELULITIS", en: "ABSCESO / CELULITIS" },
  { code: "686.9", sys: "CIE9", es: "INFECCIÓN DE DEDO DE MANO / PIE", en: "INFECCIÓN DE DEDO DE MANO / PIE" },
  { code: "692.9", sys: "CIE9", es: "DERMATITIS / ECZEMA", en: "DERMATITIS / ECZEMA" },
  { code: "693.1", sys: "CIE9", es: "ALERGIA A ALIMENTOS, DERMATITIS", en: "ALERGIA A ALIMENTOS, DERMATITIS" },
  { code: "694", sys: "CIE9", es: "DERMATOSIS AMPOLLOSA", en: "DERMATOSIS AMPOLLOSA" },
  { code: "695.9", sys: "CIE9", es: "ERITEMA SIN ESPECIFICAR", en: "ERITEMA SIN ESPECIFICAR" },
  { code: "696.0", sys: "CIE9", es: "ARTROPATÍA PSORIÁSICA", en: "ARTROPATÍA PSORIÁSICA" },
  { code: "696.1", sys: "CIE9", es: "PSORIASIS", en: "PSORIASIS" },
  { code: "698.9", sys: "CIE9", es: "PRURITO", en: "PRURITO" },
  { code: "703.0", sys: "CIE9", es: "UÑA ENCARNADA", en: "UÑA ENCARNADA" },
  { code: "708.9", sys: "CIE9", es: "URTICARIA AGUDA / CRÓNICA", en: "URTICARIA AGUDA / CRÓNICA" },
  { code: "715", sys: "CIE9", es: "ARTROSIS", en: "ARTROSIS" },
  { code: "715.90", sys: "CIE9", es: "Osteoartrosis, sitio no especificado", en: "Osteoarthrosis, unspecified whether generalized or localized, site unspecified" },
  { code: "716.9", sys: "CIE9", es: "ARTRITIS / ARTROPATÍA", en: "ARTRITIS / ARTROPATÍA" },
  { code: "719.45", sys: "CIE9", es: "COXALGIA", en: "COXALGIA" },
  { code: "72", sys: "CIE9", es: "PAROTIDITIS INFECCIOSA / PAPERAS", en: "PAROTIDITIS INFECCIOSA / PAPERAS" },
  { code: "720.2", sys: "CIE9", es: "SACROILEÍTIS", en: "SACROILEÍTIS" },
  { code: "722.10", sys: "CIE9", es: "CIÁTICA", en: "CIÁTICA" },
  { code: "723.1", sys: "CIE9", es: "CERVICALGIA / DOLOR EN CUELLO", en: "CERVICALGIA / DOLOR EN CUELLO" },
  { code: "723.5", sys: "CIE9", es: "TORTÍCOLIS", en: "TORTÍCOLIS" },
  { code: "724.2", sys: "CIE9", es: "Lumbago", en: "Lumbago" },
  { code: "724.3", sys: "CIE9", es: "LUMBOCIÁTICA", en: "LUMBOCIÁTICA" },
  { code: "724.5", sys: "CIE9", es: "DOLOR DE ESPALDA SIN ESPECIFICAR / DORSALGIA", en: "DOLOR DE ESPALDA SIN ESPECIFICAR / DORSALGIA" },
  { code: "726.32", sys: "CIE9", es: "EPICONDILITIS", en: "EPICONDILITIS" },
  { code: "726.9", sys: "CIE9", es: "TENDINITIS", en: "TENDINITIS" },
  { code: "728.7", sys: "CIE9", es: "EQUÍMOSIS ESPONTÁNEA", en: "EQUÍMOSIS ESPONTÁNEA" },
  { code: "728.83", sys: "CIE9", es: "RUPTURA MUSCULAR NO TRAUMÁTICA", en: "RUPTURA MUSCULAR NO TRAUMÁTICA" },
  { code: "728.85", sys: "CIE9", es: "ESPASMO MUSCULAR / CONTRACTURA", en: "ESPASMO MUSCULAR / CONTRACTURA" },
  { code: "729.1", sys: "CIE9", es: "FIBROMIALGIA", en: "FIBROMIALGIA" },
  { code: "729.2", sys: "CIE9", es: "NEURITIS / NEURALGIA / RADICULITIS NO ESPECIFICADA", en: "NEURITIS / NEURALGIA / RADICULITIS NO ESPECIFICADA" },
  { code: "729.5", sys: "CIE9", es: "DOLOR EN EXTREMIDADES", en: "DOLOR EN EXTREMIDADES" },
  { code: "729.82", sys: "CIE9", es: "CALAMBRE MUSCULAR", en: "CALAMBRE MUSCULAR" },
  { code: "75", sys: "CIE9", es: "MONONUCLEOSIS INFECCIOSA", en: "MONONUCLEOSIS INFECCIOSA" },
  { code: "769", sys: "CIE9", es: "DISTRÉSS RESPIRATORIO DEL RECIÉN NACIDO", en: "DISTRÉSS RESPIRATORIO DEL RECIÉN NACIDO" },
  { code: "780.0", sys: "CIE9", es: "ALTERACIÓN DE LA CONCIENCIA", en: "ALTERACIÓN DE LA CONCIENCIA" },
  { code: "780.01", sys: "CIE9", es: "COMA SIN FILIAR", en: "COMA SIN FILIAR" },
  { code: "780.09", sys: "CIE9", es: "OBNUBILACIÓN / INCONSCIENTE SIN FILIAR", en: "OBNUBILACIÓN / INCONSCIENTE SIN FILIAR" },
  { code: "780.1", sys: "CIE9", es: "ALUCINACIONES", en: "ALUCINACIONES" },
  { code: "780.2", sys: "CIE9", es: "PRESINCOPE / LIPOTIMIA / SÍNCOPE / CUADRO VEGETATIVO", en: "PRESINCOPE / LIPOTIMIA / SÍNCOPE / CUADRO VEGETATIVO" },
  { code: "780.31", sys: "CIE9", es: "CONVULSIÓN FEBRIL", en: "CONVULSIÓN FEBRIL" },
  { code: "780.39", sys: "CIE9", es: "CRISIS CONVULSIVA", en: "CRISIS CONVULSIVA" },
  { code: "780.4", sys: "CIE9", es: "MAREO / VÉRTIGO INESPECIFICO", en: "MAREO / VÉRTIGO INESPECIFICO" },
  { code: "780.52", sys: "CIE9", es: "INSOMNIO", en: "INSOMNIO" },
  { code: "780.54", sys: "CIE9", es: "HIPERSOMNIA", en: "HIPERSOMNIA" },
  { code: "780.6", sys: "CIE9", es: "Fiebre", en: "Fever" },
  { code: "780.79", sys: "CIE9", es: "ASTENIA", en: "ASTENIA" },
  { code: "780.9", sys: "CIE9", es: "DOLOR GENERALIZADO (OTROS SÍNTOMAS GENERALES)", en: "DOLOR GENERALIZADO (OTROS SÍNTOMAS GENERALES)" },
  { code: "781.0", sys: "CIE9", es: "MOVIMIENTOS INVOLUNTARIOS ANORMALES / DISTONÍA AGUDA / ESPASMO / TEMBLOR", en: "MOVIMIENTOS INVOLUNTARIOS ANORMALES / DISTONÍA AGUDA / ESPASMO / TEMBLOR" },
  { code: "781.4", sys: "CIE9", es: "PARÁLISIS TRANSITORIA DE EXTREMIDADES", en: "PARÁLISIS TRANSITORIA DE EXTREMIDADES" },
  { code: "781.6", sys: "CIE9", es: "MENINGISMO", en: "MENINGISMO" },
  { code: "781.7", sys: "CIE9", es: "TETANIA", en: "TETANIA" },
  { code: "781.9", sys: "CIE9", es: "DÉFICIT NEUROLÓGICO AGUDO SIN ESPECIFICAR", en: "DÉFICIT NEUROLÓGICO AGUDO SIN ESPECIFICAR" },
  { code: "782.0", sys: "CIE9", es: "PARESTESIAS", en: "PARESTESIAS" },
  { code: "782.1", sys: "CIE9", es: "EXANTEMA NO ESPECIFICADO", en: "EXANTEMA NO ESPECIFICADO" },
  { code: "782.3", sys: "CIE9", es: "EDEMA LOCALIZADO INESPECÍFICO / ANASARCA / HIDROPRESÍA", en: "EDEMA LOCALIZADO INESPECÍFICO / ANASARCA / HIDROPRESÍA" },
  { code: "782.4", sys: "CIE9", es: "ICTERICIA", en: "ICTERICIA" },
  { code: "782.5", sys: "CIE9", es: "CIANOSIS", en: "CIANOSIS" },
  { code: "783.0", sys: "CIE9", es: "ANOREXIA (EXCLUYE ANOREXIA NERVIOSA)", en: "ANOREXIA (EXCLUYE ANOREXIA NERVIOSA)" },
  { code: "783.2", sys: "CIE9", es: "PÉRDIDA ANORMAL DE PESO", en: "PÉRDIDA ANORMAL DE PESO" },
  { code: "784.0", sys: "CIE9", es: "Cefalea", en: "Headache" },
  { code: "784.3", sys: "CIE9", es: "AFASIA", en: "AFASIA" },
  { code: "784.49", sys: "CIE9", es: "DISFONÍA", en: "DISFONÍA" },
  { code: "784.5", sys: "CIE9", es: "DISARTRIA", en: "DISARTRIA" },
  { code: "784.7", sys: "CIE9", es: "EPISTAXIS", en: "EPISTAXIS" },
  { code: "785.0", sys: "CIE9", es: "TAQUICARDIA SIN ESPECIFICAR", en: "TAQUICARDIA SIN ESPECIFICAR" },
  { code: "785.1", sys: "CIE9", es: "PALPITACIONES", en: "PALPITACIONES" },
  { code: "785.5", sys: "CIE9", es: "SHOCK NO TRAUMÁTICO", en: "SHOCK NO TRAUMÁTICO" },
  { code: "785.50", sys: "CIE9", es: "SHOCK NO ESPECIFICADO", en: "SHOCK NO ESPECIFICADO" },
  { code: "785.51", sys: "CIE9", es: "SHOCK CARDIOGÉNICO", en: "SHOCK CARDIOGÉNICO" },
  { code: "785.59", sys: "CIE9", es: "SHOCK HIPOVOLÉMICO / SÉPTICO", en: "SHOCK HIPOVOLÉMICO / SÉPTICO" },
  { code: "785.6", sys: "CIE9", es: "GANGLIOS INFLAMADOS", en: "GANGLIOS INFLAMADOS" },
  { code: "786.03", sys: "CIE9", es: "APNEA", en: "APNEA" },
  { code: "786.09", sys: "CIE9", es: "DISNEA", en: "DISNEA" },
  { code: "786.1", sys: "CIE9", es: "ESTRIDOR", en: "ESTRIDOR" },
  { code: "786.2", sys: "CIE9", es: "TOS", en: "TOS" },
  { code: "786.3", sys: "CIE9", es: "HEMOPTISIS", en: "HEMOPTISIS" },
  { code: "786.50", sys: "CIE9", es: "DOLOR TORÁCICO NO ESPECIFICADO", en: "DOLOR TORÁCICO NO ESPECIFICADO" },
  { code: "786.51", sys: "CIE9", es: "DOLOR PRECORDIAL / ANGINOSO", en: "DOLOR PRECORDIAL / ANGINOSO" },
  { code: "786.52", sys: "CIE9", es: "DOLOR TORÁCICO PLEURÍTICO", en: "DOLOR TORÁCICO PLEURÍTICO" },
  { code: "786.59", sys: "CIE9", es: "DOLOR TORÁCICO MUSCULOESQUELÉTICO", en: "DOLOR TORÁCICO MUSCULOESQUELÉTICO" },
  { code: "786.8", sys: "CIE9", es: "HIPO", en: "HIPO" },
  { code: "787.01", sys: "CIE9", es: "VÓMITOS / NAÚSEAS SIN ESPECIFICAR", en: "VÓMITOS / NAÚSEAS SIN ESPECIFICAR" },
  { code: "787.1", sys: "CIE9", es: "PIROSIS / ACIDEZ", en: "PIROSIS / ACIDEZ" },
  { code: "787.2", sys: "CIE9", es: "DISFAGIA", en: "DISFAGIA" },
  { code: "787.3", sys: "CIE9", es: "METEORISMO", en: "METEORISMO" },
  { code: "787.91", sys: "CIE9", es: "DIARREA", en: "DIARREA" },
  { code: "788.0", sys: "CIE9", es: "CÓLICO NEFRÍTICO", en: "CÓLICO NEFRÍTICO" },
  { code: "788.1", sys: "CIE9", es: "DISURIA", en: "DISURIA" },
  { code: "788.20", sys: "CIE9", es: "RETENCIÓN URINARIA", en: "RETENCIÓN URINARIA" },
  { code: "788.5", sys: "CIE9", es: "OLIGURIA / ANURIA", en: "OLIGURIA / ANURIA" },
  { code: "788.7", sys: "CIE9", es: "URETRORREA", en: "URETRORREA" },
  { code: "789.0", sys: "CIE9", es: "CÓLICO DEL LACTANTE", en: "CÓLICO DEL LACTANTE" },
  { code: "789.00", sys: "CIE9", es: "DOLOR ABDOMINAL SITIO INESPECIFICADO", en: "DOLOR ABDOMINAL SITIO INESPECIFICADO" },
  { code: "789.06", sys: "CIE9", es: "EPIGASTRALGIA", en: "EPIGASTRALGIA" },
  { code: "789.07", sys: "CIE9", es: "ABDÓMEN AGUDO", en: "ABDÓMEN AGUDO" },
  { code: "789.5", sys: "CIE9", es: "ASCITIS", en: "ASCITIS" },
  { code: "790.6", sys: "CIE9", es: "HIPERGLUCEMIA", en: "HIPERGLUCEMIA" },
  { code: "797", sys: "CIE9", es: "PACIENTE SENIL (ENVEJECIMINETO FISIOLÓGICO)", en: "PACIENTE SENIL (ENVEJECIMINETO FISIOLÓGICO)" },
  { code: "798", sys: "CIE9", es: "MUERTE SÚBITA DE CAUSA DESCONOCIDA", en: "MUERTE SÚBITA DE CAUSA DESCONOCIDA" },
  { code: "798.0", sys: "CIE9", es: "MUERTE SÚBITA DEL LACTANTE", en: "MUERTE SÚBITA DEL LACTANTE" },
  { code: "798.1", sys: "CIE9", es: "MUERTE VIOLENTA", en: "MUERTE VIOLENTA" },
  { code: "798.2", sys: "CIE9", es: "MUERTE SIN SIGNOS DE ENFERMEDAD", en: "MUERTE SIN SIGNOS DE ENFERMEDAD" },
  { code: "798.9", sys: "CIE9", es: "MUERTE CON CONFIRMACIÓN (MUERTE SIN ASISTENCIA)", en: "MUERTE CON CONFIRMACIÓN (MUERTE SIN ASISTENCIA)" },
  { code: "799.0", sys: "CIE9", es: "ASFIXIA", en: "ASFIXIA" },
  { code: "799.1", sys: "CIE9", es: "PARADA RESPIRATORIA", en: "PARADA RESPIRATORIA" },
  { code: "799.2", sys: "CIE9", es: "NERVIOSISMO", en: "NERVIOSISMO" },
  { code: "799.3", sys: "CIE9", es: "DEBILIDAD NO ESPECIFICADA", en: "DEBILIDAD NO ESPECIFICADA" },
  { code: "799.4", sys: "CIE9", es: "CAQUEXIA", en: "CAQUEXIA" },
  { code: "803", sys: "CIE9", es: "FRACTURA DE CRÁNEO", en: "FRACTURA DE CRÁNEO" },
  { code: "805", sys: "CIE9", es: "FRACTURA DE COLUMNA VERTEBRAL", en: "FRACTURA DE COLUMNA VERTEBRAL" },
  { code: "805.4", sys: "CIE9", es: "Fractura cerrada de vértebra lumbar, sin lesión medular", en: "Closed fracture of lumbar vertebra without mention of spinal cord injury" },
  { code: "807.00", sys: "CIE9", es: "FRACTURA COSTAL CERRADA NO ESPECIFICADA", en: "FRACTURA COSTAL CERRADA NO ESPECIFICADA" },
  { code: "807.10", sys: "CIE9", es: "FRACTURA COSTAL ABIERTA NO ESPECIFICADA", en: "FRACTURA COSTAL ABIERTA NO ESPECIFICADA" },
  { code: "807.2", sys: "CIE9", es: "FRACTURA ESTERNÓN CERRADA", en: "FRACTURA ESTERNÓN CERRADA" },
  { code: "807.3", sys: "CIE9", es: "FRACTURA ESTERNÓN ABIERTA", en: "FRACTURA ESTERNÓN ABIERTA" },
  { code: "808", sys: "CIE9", es: "FRACTURA DE PELVIS", en: "FRACTURA DE PELVIS" },
  { code: "810", sys: "CIE9", es: "FRACTURA DE CLAVÍCULA", en: "FRACTURA DE CLAVÍCULA" },
  { code: "811", sys: "CIE9", es: "FRACTURA DE ESCÁPULA", en: "FRACTURA DE ESCÁPULA" },
  { code: "812", sys: "CIE9", es: "FRACTURA DE HÚMERO", en: "FRACTURA DE HÚMERO" },
  { code: "813", sys: "CIE9", es: "FRACTURA DE ANTEBRAZO", en: "FRACTURA DE ANTEBRAZO" },
  { code: "814", sys: "CIE9", es: "FRACTURA DE MUÑECA", en: "FRACTURA DE MUÑECA" },
  { code: "815", sys: "CIE9", es: "FRACTURA DE MANO", en: "FRACTURA DE MANO" },
  { code: "816", sys: "CIE9", es: "FRACTURA DE DEDOS DE LA MANO", en: "FRACTURA DE DEDOS DE LA MANO" },
  { code: "818", sys: "CIE9", es: "FRACTURAs DE MIEMBRO SUPERIOR NO ESPECIFICADAs", en: "FRACTURAs DE MIEMBRO SUPERIOR NO ESPECIFICADAs" },
  { code: "820", sys: "CIE9", es: "FRACTURA DE CADERA", en: "FRACTURA DE CADERA" },
  { code: "821.00", sys: "CIE9", es: "FRACTURA DE FÉMUR NO ESPECIFICADA", en: "FRACTURA DE FÉMUR NO ESPECIFICADA" },
  { code: "823.8", sys: "CIE9", es: "FRACTURA DE PIERNA NO ESPECIFICADA", en: "FRACTURA DE PIERNA NO ESPECIFICADA" },
  { code: "824", sys: "CIE9", es: "FRACTURA DE TOBILLO", en: "FRACTURA DE TOBILLO" },
  { code: "825", sys: "CIE9", es: "FRACTURA DE PIE", en: "FRACTURA DE PIE" },
  { code: "826", sys: "CIE9", es: "FRACTURA DE DEDOS DEL PIE", en: "FRACTURA DE DEDOS DEL PIE" },
  { code: "827", sys: "CIE9", es: "FRACTURAs DE MIEMBRO INFERIOR NO ESPECIFICADA", en: "FRACTURAs DE MIEMBRO INFERIOR NO ESPECIFICADA" },
  { code: "828", sys: "CIE9", es: "FRACTURA MÚLTIPLE MIEMBROS / COSTILLAS / ESTERNÓN", en: "FRACTURA MÚLTIPLE MIEMBROS / COSTILLAS / ESTERNÓN" },
  { code: "829.0", sys: "CIE9", es: "FRACTURA DE HUESOS CERRADA NO ESPECIFICADA", en: "FRACTURA DE HUESOS CERRADA NO ESPECIFICADA" },
  { code: "829.1", sys: "CIE9", es: "FRACTURA DE HUESOS ABIERTA NO ESPECIFICADA", en: "FRACTURA DE HUESOS ABIERTA NO ESPECIFICADA" },
  { code: "830", sys: "CIE9", es: "LUXACIÓN DE MANDÍBULA", en: "LUXACIÓN DE MANDÍBULA" },
  { code: "831", sys: "CIE9", es: "LUXACIÓN DE HOMBRO", en: "LUXACIÓN DE HOMBRO" },
  { code: "832", sys: "CIE9", es: "LUXACIÓN DE CODO", en: "LUXACIÓN DE CODO" },
  { code: "833", sys: "CIE9", es: "LUXACIÓN DE MUÑECA", en: "LUXACIÓN DE MUÑECA" },
  { code: "834", sys: "CIE9", es: "LUXACIÓN DE DEDO DE LA MANO", en: "LUXACIÓN DE DEDO DE LA MANO" },
  { code: "835", sys: "CIE9", es: "LUXACIÓN DE CADERA", en: "LUXACIÓN DE CADERA" },
  { code: "836", sys: "CIE9", es: "LUXACIÓN DE RODILLA", en: "LUXACIÓN DE RODILLA" },
  { code: "837", sys: "CIE9", es: "LUXACIÓN DE TOBILLO", en: "LUXACIÓN DE TOBILLO" },
  { code: "838", sys: "CIE9", es: "LUXACIÓN DE PIE Y DEDOS DEL PIE", en: "LUXACIÓN DE PIE Y DEDOS DEL PIE" },
  { code: "839.40", sys: "CIE9", es: "LUXACIÓN VERTEBRAL CERRADA", en: "LUXACIÓN VERTEBRAL CERRADA" },
  { code: "839.50", sys: "CIE9", es: "LUXACIÓN VERTEBRAL", en: "LUXACIÓN VERTEBRAL" },
  { code: "842.00", sys: "CIE9", es: "ESGUINCE MUÑECA", en: "ESGUINCE MUÑECA" },
  { code: "842.10", sys: "CIE9", es: "ESGUINCE MANO", en: "ESGUINCE MANO" },
  { code: "844.9", sys: "CIE9", es: "ESGUINCE RODILLA / PIERNA", en: "ESGUINCE RODILLA / PIERNA" },
  { code: "845.00", sys: "CIE9", es: "Esguince y torcedura del tobillo, no especificado", en: "Sprain of ankle, unspecified site" },
  { code: "845.10", sys: "CIE9", es: "ESGUINCE PIE", en: "ESGUINCE PIE" },
  { code: "846", sys: "CIE9", es: "ESGUINCE DE SACROILÍACA", en: "ESGUINCE DE SACROILÍACA" },
  { code: "847.0", sys: "CIE9", es: "ESGUINCE CERVICAL", en: "ESGUINCE CERVICAL" },
  { code: "848.9", sys: "CIE9", es: "ESGUINCE SIN ESPECIFICAR SITIO", en: "ESGUINCE SIN ESPECIFICAR SITIO" },
  { code: "850.9", sys: "CIE9", es: "CONMOCIÓN CEREBRAL NO ESPECÍFICA", en: "CONMOCIÓN CEREBRAL NO ESPECÍFICA" },
  { code: "851.80", sys: "CIE9", es: "CONTUSIÓN CEREBRAL SIN HERIDA", en: "CONTUSIÓN CEREBRAL SIN HERIDA" },
  { code: "851.90", sys: "CIE9", es: "CONTUSIÓN CEREBRAL CON HERIDA", en: "CONTUSIÓN CEREBRAL CON HERIDA" },
  { code: "852.00", sys: "CIE9", es: "HEMORRAGIA SUBARACNOIDEA TRAUMÁTICA SIN HERIDA", en: "HEMORRAGIA SUBARACNOIDEA TRAUMÁTICA SIN HERIDA" },
  { code: "852.10", sys: "CIE9", es: "HEMORRAGIA SUBARACNOIDEA TRAUMÁTICA CON HERIDA", en: "HEMORRAGIA SUBARACNOIDEA TRAUMÁTICA CON HERIDA" },
  { code: "852.20", sys: "CIE9", es: "HEMATOMA SUBDURAL TRAUMÁTICO SIN HERIDA", en: "HEMATOMA SUBDURAL TRAUMÁTICO SIN HERIDA" },
  { code: "852.30", sys: "CIE9", es: "HEMATOMA SUBDURAL TRAUMÁTICO CON HERIDA", en: "HEMATOMA SUBDURAL TRAUMÁTICO CON HERIDA" },
  { code: "852.40", sys: "CIE9", es: "HEMATOMA EPIDURAL TRAUMÁTICO SIN HERIDA", en: "HEMATOMA EPIDURAL TRAUMÁTICO SIN HERIDA" },
  { code: "852.50", sys: "CIE9", es: "HEMATOMA EPIDURAL TRAUMÁTICO CON HERIDA", en: "HEMATOMA EPIDURAL TRAUMÁTICO CON HERIDA" },
  { code: "854.00", sys: "CIE9", es: "TRAUMATISMO CRANEOENCEFÁLICO", en: "TRAUMATISMO CRANEOENCEFÁLICO" },
  { code: "854.01", sys: "CIE9", es: "TRAUMATISMO CRANEOENCEFÁLICO SIN PÉRDIDA DE CONOCIMIENTO", en: "TRAUMATISMO CRANEOENCEFÁLICO SIN PÉRDIDA DE CONOCIMIENTO" },
  { code: "860", sys: "CIE9", es: "NEUMOTÓRAX / HEMOTÓRAX TRAUMÁTICO", en: "NEUMOTÓRAX / HEMOTÓRAX TRAUMÁTICO" },
  { code: "862", sys: "CIE9", es: "TRAUMATISMO TORÁCICO", en: "TRAUMATISMO TORÁCICO" },
  { code: "868", sys: "CIE9", es: "TRAUMATISMO ABDOMINAL", en: "TRAUMATISMO ABDOMINAL" },
  { code: "869.1", sys: "CIE9", es: "EVISCERACIÓN TRAUMÁTICA", en: "EVISCERACIÓN TRAUMÁTICA" },
  { code: "870", sys: "CIE9", es: "HERIDA EN ANEXOS OCULARES", en: "HERIDA EN ANEXOS OCULARES" },
  { code: "871.4", sys: "CIE9", es: "HERIDA NO ESPECIFICADA OCULAR", en: "HERIDA NO ESPECIFICADA OCULAR" },
  { code: "871.6", sys: "CIE9", es: "CUERPO EXTRAÑO CON PENETRACIÓN EN GLOBO OCULAR", en: "CUERPO EXTRAÑO CON PENETRACIÓN EN GLOBO OCULAR" },
  { code: "873.0", sys: "CIE9", es: "HERIDA EN CUERO CABELLUDO NO COMPLICADA", en: "HERIDA EN CUERO CABELLUDO NO COMPLICADA" },
  { code: "873.1", sys: "CIE9", es: "SCALP (HERIDA ABIERTA DE CUERO CABELLUDO COMPLICADA)", en: "SCALP (HERIDA ABIERTA DE CUERO CABELLUDO COMPLICADA)" },
  { code: "873.40", sys: "CIE9", es: "HERIDA EN CARA", en: "HERIDA EN CARA" },
  { code: "873.60", sys: "CIE9", es: "HERIDA EN BOCA", en: "HERIDA EN BOCA" },
  { code: "874.8", sys: "CIE9", es: "HERIDA EN CUELLO", en: "HERIDA EN CUELLO" },
  { code: "875", sys: "CIE9", es: "HERIDA EN TÓRAX", en: "HERIDA EN TÓRAX" },
  { code: "876", sys: "CIE9", es: "HERIDA EN ESPALDA", en: "HERIDA EN ESPALDA" },
  { code: "877", sys: "CIE9", es: "HERIDA EN GLÚTEOS", en: "HERIDA EN GLÚTEOS" },
  { code: "878", sys: "CIE9", es: "HERIDA EN GENITALES EXTERNOS", en: "HERIDA EN GENITALES EXTERNOS" },
  { code: "879.2", sys: "CIE9", es: "HERIDA EN ABDÓMEN", en: "HERIDA EN ABDÓMEN" },
  { code: "879.8", sys: "CIE9", es: "HERIDA DE LOCALIZACIÓN NO ESPECIFICADA NO COMPLICADA", en: "HERIDA DE LOCALIZACIÓN NO ESPECIFICADA NO COMPLICADA" },
  { code: "879.9", sys: "CIE9", es: "HERIDA DE LOCALIZACIÓN NO ESPECIFICADA COMPLICADA", en: "HERIDA DE LOCALIZACIÓN NO ESPECIFICADA COMPLICADA" },
  { code: "880", sys: "CIE9", es: "HERIDA EN MIEMBRO SUPERIOR (HOMBRO / BRAZO)", en: "HERIDA EN MIEMBRO SUPERIOR (HOMBRO / BRAZO)" },
  { code: "881", sys: "CIE9", es: "HERIDA EN MIEMBRO SUPERIOR (CODO / ANTEBRAZO / MUÑECA)", en: "HERIDA EN MIEMBRO SUPERIOR (CODO / ANTEBRAZO / MUÑECA)" },
  { code: "882", sys: "CIE9", es: "HERIDA EN MANO", en: "HERIDA EN MANO" },
  { code: "882.1", sys: "CIE9", es: "HERIDA EN MANO COMPLICADA", en: "HERIDA EN MANO COMPLICADA" },
  { code: "883", sys: "CIE9", es: "HERIDA EN DEDOS DE LA MANO", en: "HERIDA EN DEDOS DE LA MANO" },
  { code: "884", sys: "CIE9", es: "HERIDA MÚLTIPLE EN EXTREMIDAD SUPERIOR NO ESPECIFICADA", en: "HERIDA MÚLTIPLE EN EXTREMIDAD SUPERIOR NO ESPECIFICADA" },
  { code: "885", sys: "CIE9", es: "AMPUTACIÓN TRAUMÁTICA DEDO PULGAR", en: "AMPUTACIÓN TRAUMÁTICA DEDO PULGAR" },
  { code: "886", sys: "CIE9", es: "AMPUTACIÓN TRAUMÁTICA DEDO MANO", en: "AMPUTACIÓN TRAUMÁTICA DEDO MANO" },
  { code: "887", sys: "CIE9", es: "AMPUTACIÓN TRAUMÁTICA BRAZO / MANO", en: "AMPUTACIÓN TRAUMÁTICA BRAZO / MANO" },
  { code: "890", sys: "CIE9", es: "HERIDA EN MIEMBRO INFERIOR (CADERA / MUSLO)", en: "HERIDA EN MIEMBRO INFERIOR (CADERA / MUSLO)" },
  { code: "891.0", sys: "CIE9", es: "HERIDA EN PIERNA / RODILLA / TOBILLO", en: "HERIDA EN PIERNA / RODILLA / TOBILLO" },
  { code: "892.0", sys: "CIE9", es: "HERIDA EN PIE", en: "HERIDA EN PIE" },
  { code: "892.1", sys: "CIE9", es: "HERIDA EN PIE COMPLICADA", en: "HERIDA EN PIE COMPLICADA" },
  { code: "893.0", sys: "CIE9", es: "HERIDA EN DEDO DEL PIE", en: "HERIDA EN DEDO DEL PIE" },
  { code: "894", sys: "CIE9", es: "HERIDA MÚLTIPLE EN MIEMBRO INFERIOR", en: "HERIDA MÚLTIPLE EN MIEMBRO INFERIOR" },
  { code: "895", sys: "CIE9", es: "AMPUTACIÓN TRAUMÁTICA DEDO PIE", en: "AMPUTACIÓN TRAUMÁTICA DEDO PIE" },
  { code: "896", sys: "CIE9", es: "AMPUTACIÓN TRAUMÁTICA PIE", en: "AMPUTACIÓN TRAUMÁTICA PIE" },
  { code: "897", sys: "CIE9", es: "AMPUTACIÓN TRAUMÁTICA PIERNA", en: "AMPUTACIÓN TRAUMÁTICA PIERNA" },
  { code: "904.9", sys: "CIE9", es: "HEMATOMA SIN ESPECIFICAR", en: "HEMATOMA SIN ESPECIFICAR" },
  { code: "920", sys: "CIE9", es: "CONTUSIÓN CRÁNEO / CUERO CABELLUDO / CARA / CUELLO (EXCEPTO OJO)", en: "CONTUSIÓN CRÁNEO / CUERO CABELLUDO / CARA / CUELLO (EXCEPTO OJO)" },
  { code: "921.9", sys: "CIE9", es: "CONTUSIÓN OCULAR", en: "CONTUSIÓN OCULAR" },
  { code: "922.1", sys: "CIE9", es: "CONTUSIÓN EN TÓRAX", en: "CONTUSIÓN EN TÓRAX" },
  { code: "922.2", sys: "CIE9", es: "CONTUSIÓN ABDOMINAL", en: "CONTUSIÓN ABDOMINAL" },
  { code: "922.31", sys: "CIE9", es: "CONTUSIÓN EN ESPALDA", en: "CONTUSIÓN EN ESPALDA" },
  { code: "922.4", sys: "CIE9", es: "CONTUSIÓN EN ÓRGANOS GENITALES EXTERNOS", en: "CONTUSIÓN EN ÓRGANOS GENITALES EXTERNOS" },
  { code: "923.9", sys: "CIE9", es: "CONTUSIÓN EN MIEMBROS SUPERIORES", en: "CONTUSIÓN EN MIEMBROS SUPERIORES" },
  { code: "924.5", sys: "CIE9", es: "CONTUSIÓN EN MIEMBROS INFERIORES", en: "CONTUSIÓN EN MIEMBROS INFERIORES" },
  { code: "924.8", sys: "CIE9", es: "POLICONTUSIONADO (CONTUSIÓN EN MÚLTIPLES SITIOS)", en: "POLICONTUSIONADO (CONTUSIÓN EN MÚLTIPLES SITIOS)" },
  { code: "930.9", sys: "CIE9", es: "CUERPO EXTRAÑO EN SUPERFICIE OCULAR NO ESPECIFICADO", en: "CUERPO EXTRAÑO EN SUPERFICIE OCULAR NO ESPECIFICADO" },
  { code: "931", sys: "CIE9", es: "CUERPO EXTRAÑO EN OIDO (E: CE CUALQUIER ORIFICIO)", en: "CUERPO EXTRAÑO EN OIDO (E: CE CUALQUIER ORIFICIO)" },
  { code: "932", sys: "CIE9", es: "CUERPO EXTRAÑO NASAL", en: "CUERPO EXTRAÑO NASAL" },
  { code: "933.1", sys: "CIE9", es: "ASFIXIA (ALIMENTO / CUERPO EXTRAÑO)", en: "ASFIXIA (ALIMENTO / CUERPO EXTRAÑO)" },
  { code: "934.9", sys: "CIE9", es: "BRONCOASPIRACIÓN", en: "BRONCOASPIRACIÓN" },
  { code: "935", sys: "CIE9", es: "CUERPO EXTRAÑO EN TUBO DIGESTIVO SUPERIOR", en: "CUERPO EXTRAÑO EN TUBO DIGESTIVO SUPERIOR" },
  { code: "936", sys: "CIE9", es: "CUERPO EXTRAÑO EN TUBO DIGESTIVO INFERIOR", en: "CUERPO EXTRAÑO EN TUBO DIGESTIVO INFERIOR" },
  { code: "937", sys: "CIE9", es: "CUERPO EXTRAÑO EN RECTO / ANO (E: CE CUALQUIER ORIFICIO)", en: "CUERPO EXTRAÑO EN RECTO / ANO (E: CE CUALQUIER ORIFICIO)" },
  { code: "939.2", sys: "CIE9", es: "CUERPO EXTRAÑO VAGINA (E: CE CUALQUIER ORIFICIO)", en: "CUERPO EXTRAÑO VAGINA (E: CE CUALQUIER ORIFICIO)" },
  { code: "939.9", sys: "CIE9", es: "CUERPO EXTRAÑO EN TRACTO GENITOURINARIO NO ESPECIFICADO", en: "CUERPO EXTRAÑO EN TRACTO GENITOURINARIO NO ESPECIFICADO" },
  { code: "940.9", sys: "CIE9", es: "QUEMADURA OCULAR Y/O EN ANEXOS", en: "QUEMADURA OCULAR Y/O EN ANEXOS" },
  { code: "941.00", sys: "CIE9", es: "QUEMADURA CABEZA / CARA (EXCLUYE BOCA)", en: "QUEMADURA CABEZA / CARA (EXCLUYE BOCA)" },
  { code: "941.08", sys: "CIE9", es: "QUEMADURA CUELLO", en: "QUEMADURA CUELLO" },
  { code: "941.09", sys: "CIE9", es: "QUEMADURA MÚLTIPLE CABEZA / CARA / CUELLO", en: "QUEMADURA MÚLTIPLE CABEZA / CARA / CUELLO" },
  { code: "942.00", sys: "CIE9", es: "QUEMADURA EN TRONCO NO ESPECIFICADA", en: "QUEMADURA EN TRONCO NO ESPECIFICADA" },
  { code: "942.02", sys: "CIE9", es: "QUEMADURA EN TÓRAX", en: "QUEMADURA EN TÓRAX" },
  { code: "942.03", sys: "CIE9", es: "QUEMADURA ABDÓMEN", en: "QUEMADURA ABDÓMEN" },
  { code: "942.04", sys: "CIE9", es: "QUEMADURA EN ESPALDA", en: "QUEMADURA EN ESPALDA" },
  { code: "943.00", sys: "CIE9", es: "QUEMADURA EN MIEMBROS SUPERIORES (EXCEPTO MANO)", en: "QUEMADURA EN MIEMBROS SUPERIORES (EXCEPTO MANO)" },
  { code: "944.00", sys: "CIE9", es: "QUEMADURA EN MANO", en: "QUEMADURA EN MANO" },
  { code: "944.07", sys: "CIE9", es: "QUEMADURA EN MUÑECA", en: "QUEMADURA EN MUÑECA" },
  { code: "945.00", sys: "CIE9", es: "QUEMADURA EN MIEMBROS INFERIORES", en: "QUEMADURA EN MIEMBROS INFERIORES" },
  { code: "947.0", sys: "CIE9", es: "QUEMADURA EN BOCA", en: "QUEMADURA EN BOCA" },
  { code: "949.0", sys: "CIE9", es: "QUEMADURA", en: "QUEMADURA" },
  { code: "949.1", sys: "CIE9", es: "QUEMADURAS DE PRIMER GRADO", en: "QUEMADURAS DE PRIMER GRADO" },
  { code: "949.2", sys: "CIE9", es: "QUEMADURA DE SEGUNDO GRADO", en: "QUEMADURA DE SEGUNDO GRADO" },
  { code: "949.3", sys: "CIE9", es: "QUEMADURA DE TERCER GRADO", en: "QUEMADURA DE TERCER GRADO" },
  { code: "952.0", sys: "CIE9", es: "TRAUMATISMO MÉDULA CERVICAL", en: "TRAUMATISMO MÉDULA CERVICAL" },
  { code: "952.1", sys: "CIE9", es: "TRAUMATISMO MÉDULA DORSAL", en: "TRAUMATISMO MÉDULA DORSAL" },
  { code: "952.2", sys: "CIE9", es: "TRAUMATISMO MÉDULA LUMBAR", en: "TRAUMATISMO MÉDULA LUMBAR" },
  { code: "952.9", sys: "CIE9", es: "TRAUMATISMO MEDULAR NO ESPECIFICADO", en: "TRAUMATISMO MEDULAR NO ESPECIFICADO" },
  { code: "958.0", sys: "CIE9", es: "EMBOLIA GASEOSA", en: "EMBOLIA GASEOSA" },
  { code: "958.1", sys: "CIE9", es: "EMBOLIA GRASA", en: "EMBOLIA GRASA" },
  { code: "958.4", sys: "CIE9", es: "SHOCK TRAUMATICO", en: "SHOCK TRAUMATICO" },
  { code: "958.7", sys: "CIE9", es: "ENFISEMA SUBCUTÁNEO TRAUMÁTICO", en: "ENFISEMA SUBCUTÁNEO TRAUMÁTICO" },
  { code: "959.01", sys: "CIE9", es: "TRAUMATISMO EN CABEZA", en: "TRAUMATISMO EN CABEZA" },
  { code: "959.09", sys: "CIE9", es: "TRAUMATISMO EN CARA / CUELLO", en: "TRAUMATISMO EN CARA / CUELLO" },
  { code: "959.1", sys: "CIE9", es: "TRAUMATISMO EN TRONCO", en: "TRAUMATISMO EN TRONCO" },
  { code: "959.2", sys: "CIE9", es: "TRAUMATISMO EN MIEMBROS SUPERIORES (HOMBRO Y BRAZO)", en: "TRAUMATISMO EN MIEMBROS SUPERIORES (HOMBRO Y BRAZO)" },
  { code: "959.3", sys: "CIE9", es: "TRAUMATISMO EN MIEMBROS SUPERIORES (CODO, ANTEBRAZO, MUÑECA)", en: "TRAUMATISMO EN MIEMBROS SUPERIORES (CODO, ANTEBRAZO, MUÑECA)" },
  { code: "959.4", sys: "CIE9", es: "TRAUMATISMO EN MIEMBROS SUPERIORES (MANO EXCEPTO DEDO)", en: "TRAUMATISMO EN MIEMBROS SUPERIORES (MANO EXCEPTO DEDO)" },
  { code: "959.5", sys: "CIE9", es: "TRAUMATISMO EN MIMEBROS SUPERIORES (DEDO)", en: "TRAUMATISMO EN MIMEBROS SUPERIORES (DEDO)" },
  { code: "959.6", sys: "CIE9", es: "TRAUMATISMO EN MIEMBROS INFERIORES (CADERA, MUSLO)", en: "TRAUMATISMO EN MIEMBROS INFERIORES (CADERA, MUSLO)" },
  { code: "959.7", sys: "CIE9", es: "TRAUMATISMO EN MIEMBROS INFERIORES (RODILLA, PIERNA, TOBILLO, PIE)", en: "TRAUMATISMO EN MIEMBROS INFERIORES (RODILLA, PIERNA, TOBILLO, PIE)" },
  { code: "959.8", sys: "CIE9", es: "POLITRAUMATIZADO", en: "POLITRAUMATIZADO" },
  { code: "959.9", sys: "CIE9", es: "TRAUMATISMO EN LUGAR NO ESPECIFICADO", en: "TRAUMATISMO EN LUGAR NO ESPECIFICADO" },
  { code: "965.00", sys: "CIE9", es: "INTOXICACIÓN POR OPIO", en: "INTOXICACIÓN POR OPIO" },
  { code: "965.01", sys: "CIE9", es: "INTOXICACIÓN POR HEROINA", en: "INTOXICACIÓN POR HEROINA" },
  { code: "965.02", sys: "CIE9", es: "INTOXICACIÓN POR METADONA", en: "INTOXICACIÓN POR METADONA" },
  { code: "965.09", sys: "CIE9", es: "INTOXICACIÓN POR OPIÁCEOS (CODEINA / MORFINA / MEPERIDINA)", en: "INTOXICACIÓN POR OPIÁCEOS (CODEINA / MORFINA / MEPERIDINA)" },
  { code: "965.1", sys: "CIE9", es: "INTOXICACIÓN POR SALICILATOS", en: "INTOXICACIÓN POR SALICILATOS" },
  { code: "965.9", sys: "CIE9", es: "INTOXICACIÓN POR ANALGÉSICOS", en: "INTOXICACIÓN POR ANALGÉSICOS" },
  { code: "966.3", sys: "CIE9", es: "INTOXICACIÓN POR ANTICONVULSIVANTES (EXCEPTO BARBITÚRICOS Y SULFANAMIDAS)", en: "INTOXICACIÓN POR ANTICONVULSIVANTES (EXCEPTO BARBITÚRICOS Y SULFANAMIDAS)" },
  { code: "967.0", sys: "CIE9", es: "INTOXICACIÓN POR BARBITÚRICOS", en: "INTOXICACIÓN POR BARBITÚRICOS" },
  { code: "968.5", sys: "CIE9", es: "INTOXICACIÓN POR COCAINA", en: "INTOXICACIÓN POR COCAINA" },
  { code: "969.0", sys: "CIE9", es: "INTOXICACIÓN POR ANTIDEPRESIVOS", en: "INTOXICACIÓN POR ANTIDEPRESIVOS" },
  { code: "969.4", sys: "CIE9", es: "INTOXICACION POR BENZODIACEPINAS", en: "INTOXICACION POR BENZODIACEPINAS" },
  { code: "969.6", sys: "CIE9", es: "INTOXICACIÓN POR ALUCINOGENOS / CANNABIS / LSD", en: "INTOXICACIÓN POR ALUCINOGENOS / CANNABIS / LSD" },
  { code: "969.7", sys: "CIE9", es: "INTOXICACIÓN POR ANFETAMINAS / CAFEINA", en: "INTOXICACIÓN POR ANFETAMINAS / CAFEINA" },
  { code: "977.9", sys: "CIE9", es: "SOBREDOSIS DROGAS", en: "SOBREDOSIS DROGAS" },
  { code: "986", sys: "CIE9", es: "INTOXICACIÓN POR MONÓXIDO DE CARBONO", en: "INTOXICACIÓN POR MONÓXIDO DE CARBONO" },
  { code: "987.9", sys: "CIE9", es: "INTENTO DE AUTOLISIS POR INHALACIÓN DE GASES", en: "INTENTO DE AUTOLISIS POR INHALACIÓN DE GASES" },
  { code: "988.1", sys: "CIE9", es: "INTOXICACIÓN POR SETAS / HONGOS", en: "INTOXICACIÓN POR SETAS / HONGOS" },
  { code: "989.9", sys: "CIE9", es: "INTOXICACIÓN POR PRODUCTOS NO MEDICAMENTOSOS", en: "INTOXICACIÓN POR PRODUCTOS NO MEDICAMENTOSOS" },
  { code: "99.60", sys: "CIE9", es: "REANIMACIÓN CARDIOPULMONAR", en: "REANIMACIÓN CARDIOPULMONAR" },
  { code: "991.3", sys: "CIE9", es: "CONGELACIÓN (CAUSA EXTERNA FRÍO EXCESIVO)", en: "CONGELACIÓN (CAUSA EXTERNA FRÍO EXCESIVO)" },
  { code: "991.5", sys: "CIE9", es: "SABAÑONES", en: "SABAÑONES" },
  { code: "991.6", sys: "CIE9", es: "HIPOTERMIA ACCIDENTAL AMBIENTAL", en: "HIPOTERMIA ACCIDENTAL AMBIENTAL" },
  { code: "992.0", sys: "CIE9", es: "GOLPE DE CALOR (INSOLACIÓN)", en: "GOLPE DE CALOR (INSOLACIÓN)" },
  { code: "992.1", sys: "CIE9", es: "SINCOPE POR CALOR", en: "SINCOPE POR CALOR" },
  { code: "993.2", sys: "CIE9", es: "MAL DE MONTAÑA / MAL DE ALTURA", en: "MAL DE MONTAÑA / MAL DE ALTURA" },
  { code: "993.3", sys: "CIE9", es: "DESCOMPRESIÓN", en: "DESCOMPRESIÓN" },
  { code: "993.9", sys: "CIE9", es: "BAROTRAUMA", en: "BAROTRAUMA" },
  { code: "994.1", sys: "CIE9", es: "AHOGAMIENTO Y SUMERSIÓN NO FATAL", en: "AHOGAMIENTO Y SUMERSIÓN NO FATAL" },
  { code: "994.7", sys: "CIE9", es: "AHORCAMIENTO / ESTRANGULACIÓN", en: "AHORCAMIENTO / ESTRANGULACIÓN" },
  { code: "994.8", sys: "CIE9", es: "ELECTROCUCIÓN / FULGURACIÓN", en: "ELECTROCUCIÓN / FULGURACIÓN" },
  { code: "995.0", sys: "CIE9", es: "REACCIÓN ANAFILÁCTICA / SHOCK / ANAFILAXIA", en: "REACCIÓN ANAFILÁCTICA / SHOCK / ANAFILAXIA" },
  { code: "995.1", sys: "CIE9", es: "EDEMA ANGIONEURÓTICO", en: "EDEMA ANGIONEURÓTICO" },
  { code: "995.2", sys: "CIE9", es: "REACCIÓN ALÉRGICA O EFECTO ADVERSO A FÁRMACOS", en: "REACCIÓN ALÉRGICA O EFECTO ADVERSO A FÁRMACOS" },
  { code: "995.3", sys: "CIE9", es: "REACCIÓN ALÉRGICA NO ESPECIFICADA", en: "REACCIÓN ALÉRGICA NO ESPECIFICADA" },
  { code: "995.50", sys: "CIE9", es: "MALOS TRATOS INFANTILES SIN ESPECIFICAR", en: "MALOS TRATOS INFANTILES SIN ESPECIFICAR" },
  { code: "995.52", sys: "CIE9", es: "ABANDONO DE NIÑOS (ALIMENTICIO)", en: "ABANDONO DE NIÑOS (ALIMENTICIO)" },
  { code: "995.53", sys: "CIE9", es: "VIOLACIÓN A MENORES", en: "VIOLACIÓN A MENORES" },
  { code: "995.54", sys: "CIE9", es: "MALOS TRATOS FÍSICOS A MENORES", en: "MALOS TRATOS FÍSICOS A MENORES" },
  { code: "995.55", sys: "CIE9", es: "SÍNDROME DEL NIÑO MALTRATADO", en: "SÍNDROME DEL NIÑO MALTRATADO" },
  { code: "995.69", sys: "CIE9", es: "SHOCK ANAFILÁCTICO POR REACCIÓN ALÉRGICA A ALIMENTOS", en: "SHOCK ANAFILÁCTICO POR REACCIÓN ALÉRGICA A ALIMENTOS" },
  { code: "995.80", sys: "CIE9", es: "MALOS TRATOS A ADULTOS SIN ESPECIFICAR", en: "MALOS TRATOS A ADULTOS SIN ESPECIFICAR" },
  { code: "995.81", sys: "CIE9", es: "MALOS TRATOS FÍSICOS A ADULTOS", en: "MALOS TRATOS FÍSICOS A ADULTOS" },
  { code: "995.83", sys: "CIE9", es: "VIOLACIÓN A ADULTOS", en: "VIOLACIÓN A ADULTOS" },
  { code: "995.86", sys: "CIE9", es: "HIPERTERMIA MALIGNA", en: "HIPERTERMIA MALIGNA" },
  { code: "995.89", sys: "CIE9", es: "HIPOTERMIA DEBIDA A ANESTESIA", en: "HIPOTERMIA DEBIDA A ANESTESIA" },
  { code: "996.01", sys: "CIE9", es: "MALFUNCIONAMIENTO DE MARCAPASOS", en: "MALFUNCIONAMIENTO DE MARCAPASOS" },
  { code: "996.76", sys: "CIE9", es: "OBSTRUCCIÓN SONDA VESICAL", en: "OBSTRUCCIÓN SONDA VESICAL" },
  { code: "996.78", sys: "CIE9", es: "OBSTRUCCIÓN SONDA NASOGÁSTRICA", en: "OBSTRUCCIÓN SONDA NASOGÁSTRICA" },
  { code: "998.11", sys: "CIE9", es: "HEMORRAGIA QUE COMPLICA UN PROCEDIMIENTO", en: "HEMORRAGIA QUE COMPLICA UN PROCEDIMIENTO" },
  { code: "998.5", sys: "CIE9", es: "INFECCIÓN POSTOPERATORIA", en: "INFECCIÓN POSTOPERATORIA" },
  { code: "998.83", sys: "CIE9", es: "HERIDA QUIRÚRGICA SIN CICATRIZAR", en: "HERIDA QUIRÚRGICA SIN CICATRIZAR" },
  { code: "E807", sys: "CIE9", es: "ACCIDENTE FERROVIARIO", en: "ACCIDENTE FERROVIARIO" },
  { code: "E814.7", sys: "CIE9", es: "ATROPELLO", en: "ATROPELLO" },
  { code: "E819", sys: "CIE9", es: "ACCIDENTE DE TRÁFICO", en: "ACCIDENTE DE TRÁFICO" },
  { code: "E826", sys: "CIE9", es: "ACCIDENTE DE BICICLETA", en: "ACCIDENTE DE BICICLETA" },
  { code: "E838", sys: "CIE9", es: "ACCIDENTE EN MEDIO DE TRANSPORTE ACUÁTICO", en: "ACCIDENTE EN MEDIO DE TRANSPORTE ACUÁTICO" },
  { code: "E841", sys: "CIE9", es: "ACCIDENTE AÉREO", en: "ACCIDENTE AÉREO" },
  { code: "E848", sys: "CIE9", es: "ACCIDENTE DE OTROS VEHÍCULOS", en: "ACCIDENTE DE OTROS VEHÍCULOS" },
  { code: "E849.0", sys: "CIE9", es: "LUGAR HOGAR", en: "LUGAR HOGAR" },
  { code: "E849.1", sys: "CIE9", es: "LUGAR GRANJA", en: "LUGAR GRANJA" },
  { code: "E849.2", sys: "CIE9", es: "LUGAR MINA - CANTERA", en: "LUGAR MINA - CANTERA" },
  { code: "E849.3", sys: "CIE9", es: "LUGAR LOCAL INDUSTRIAL", en: "LUGAR LOCAL INDUSTRIAL" },
  { code: "E849.4", sys: "CIE9", es: "LUGAR RECREO - DEPORTE", en: "LUGAR RECREO - DEPORTE" },
  { code: "E849.5", sys: "CIE9", es: "LUGAR CALLE - VÍA PÚBLICA", en: "LUGAR CALLE - VÍA PÚBLICA" },
  { code: "E849.6", sys: "CIE9", es: "LUGAR EDIFICIO PÚBLICO", en: "LUGAR EDIFICIO PÚBLICO" },
  { code: "E849.7", sys: "CIE9", es: "LUGAR INSTITUCIÓN (RESIDENCIAL - PRISIÓN - HOSPITAL)", en: "LUGAR INSTITUCIÓN (RESIDENCIAL - PRISIÓN - HOSPITAL)" },
  { code: "E849.8", sys: "CIE9", es: "LUGAR OTROS SITIOS", en: "LUGAR OTROS SITIOS" },
  { code: "E849.9", sys: "CIE9", es: "LUGAR SITIO NO ESPECIFICADO", en: "LUGAR SITIO NO ESPECIFICADO" },
  { code: "E858.9", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE FÁRMACO SIN ESPECIFICAR", en: "INTOXICACIÓN ACCIDENTAL DE FÁRMACO SIN ESPECIFICAR" },
  { code: "E860.0", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE BEBIDAS ALCOHÓLICAS", en: "INTOXICACIÓN ACCIDENTAL DE BEBIDAS ALCOHÓLICAS" },
  { code: "E860.2", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE ALCOHOL METÍLICO", en: "INTOXICACIÓN ACCIDENTAL DE ALCOHOL METÍLICO" },
  { code: "E860.9", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE ALCOHOL NO ESPECIFICADO", en: "INTOXICACIÓN ACCIDENTAL DE ALCOHOL NO ESPECIFICADO" },
  { code: "E861", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE PINTURAS, BARNICES, DESINFECTANTES Y AGENTES DE LIMPIEZA Y PULIDO", en: "INTOXICACIÓN ACCIDENTAL DE PINTURAS, BARNICES, DESINFECTANTES Y AGENTES DE LIMPIEZA Y PULIDO" },
  { code: "E862", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE DERIVADOS DEL PETRÓLEO Y DISOLVENTES", en: "INTOXICACIÓN ACCIDENTAL DE DERIVADOS DEL PETRÓLEO Y DISOLVENTES" },
  { code: "E863", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE INSECTICIDAS Y HERBICIDAS", en: "INTOXICACIÓN ACCIDENTAL DE INSECTICIDAS Y HERBICIDAS" },
  { code: "E864", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE CORROSIVOS Y CAÚSTICOS", en: "INTOXICACIÓN ACCIDENTAL DE CORROSIVOS Y CAÚSTICOS" },
  { code: "E865", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE ALIMENTOS TÓXICOS Y PLANTAS VENENOSAS", en: "INTOXICACIÓN ACCIDENTAL DE ALIMENTOS TÓXICOS Y PLANTAS VENENOSAS" },
  { code: "E866.1", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE MERCURIO", en: "INTOXICACIÓN ACCIDENTAL DE MERCURIO" },
  { code: "E866.5", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE ABONOS PARA PLANTAS", en: "INTOXICACIÓN ACCIDENTAL DE ABONOS PARA PLANTAS" },
  { code: "E866.6", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE PEGAMENTOS Y ADHESIVOS", en: "INTOXICACIÓN ACCIDENTAL DE PEGAMENTOS Y ADHESIVOS" },
  { code: "E866.7", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE COSMÉTICOS", en: "INTOXICACIÓN ACCIDENTAL DE COSMÉTICOS" },
  { code: "E867", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE GAS DE TUBERÍA", en: "INTOXICACIÓN ACCIDENTAL DE GAS DE TUBERÍA" },
  { code: "E868.0", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE GAS EN CONTENEDOR", en: "INTOXICACIÓN ACCIDENTAL DE GAS EN CONTENEDOR" },
  { code: "E868.2", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE GAS DE ESCAPE DE VEHÍCULOS", en: "INTOXICACIÓN ACCIDENTAL DE GAS DE ESCAPE DE VEHÍCULOS" },
  { code: "E868.3", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE MONÓXIDO DOMESTICO", en: "INTOXICACIÓN ACCIDENTAL DE MONÓXIDO DOMESTICO" },
  { code: "E868.8", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE MONÓXIDO INDUSTRIAL", en: "INTOXICACIÓN ACCIDENTAL DE MONÓXIDO INDUSTRIAL" },
  { code: "E869.3", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE GAS LACRIMÓGENO", en: "INTOXICACIÓN ACCIDENTAL DE GAS LACRIMÓGENO" },
  { code: "E869.9", sys: "CIE9", es: "INTOXICACIÓN ACCIDENTAL DE GAS, VAPOR SIN ESPECIFICAR", en: "INTOXICACIÓN ACCIDENTAL DE GAS, VAPOR SIN ESPECIFICAR" },
  { code: "E870", sys: "CIE9", es: "ACCIDENTE EN LA PRÁCTICA DE CUIDADOS MÉDICOS", en: "ACCIDENTE EN LA PRÁCTICA DE CUIDADOS MÉDICOS" },
  { code: "E873", sys: "CIE9", es: "SOBREDOSIS POR FALLO EN LA TERAPIA MEDICA (EXCLUYE SOBREDOSIS ACCIDENTAL)", en: "SOBREDOSIS POR FALLO EN LA TERAPIA MEDICA (EXCLUYE SOBREDOSIS ACCIDENTAL)" },
  { code: "E880", sys: "CIE9", es: "CAIDA POR ESCALERAS", en: "CAIDA POR ESCALERAS" },
  { code: "E881", sys: "CIE9", es: "CAIDA DESDE ESCALERAS DE MANO O ANDAMIOS", en: "CAIDA DESDE ESCALERAS DE MANO O ANDAMIOS" },
  { code: "E884.9", sys: "CIE9", es: "OTRAS CAÍDAS DESDE UN NIVEL A OTRO / PRECIPITADO", en: "OTRAS CAÍDAS DESDE UN NIVEL A OTRO / PRECIPITADO" },
  { code: "E885", sys: "CIE9", es: "CAIDA POR RESBALÓN, TRASPIÉS O TROPIEZO", en: "CAIDA POR RESBALÓN, TRASPIÉS O TROPIEZO" },
  { code: "E886.0", sys: "CIE9", es: "CAIDA DURANTE DEPORTE", en: "CAIDA DURANTE DEPORTE" },
  { code: "E887", sys: "CIE9", es: "FRACTURA SIN ESPECIFICAR CAUSA", en: "FRACTURA SIN ESPECIFICAR CAUSA" },
  { code: "E888", sys: "CIE9", es: "CAIDA ACCIDENTAL SIN ESPECIFICAR", en: "CAIDA ACCIDENTAL SIN ESPECIFICAR" },
  { code: "E899", sys: "CIE9", es: "INCENDIO", en: "INCENDIO" },
  { code: "E900.9", sys: "CIE9", es: "CALOR EXCESIVO DE ORIGEN NO ESPECIFICADO", en: "CALOR EXCESIVO DE ORIGEN NO ESPECIFICADO" },
  { code: "E901.9", sys: "CIE9", es: "FRÍO EXCESIVO DE ORIGEN NO ESPECIFICADO", en: "FRÍO EXCESIVO DE ORIGEN NO ESPECIFICADO" },
  { code: "E902.9", sys: "CIE9", es: "CAMBIOS DE PRESIÓN ATMOSFÉRICA DE CAUSA NO ESPECIFICADA", en: "CAMBIOS DE PRESIÓN ATMOSFÉRICA DE CAUSA NO ESPECIFICADA" },
  { code: "E904", sys: "CIE9", es: "HAMBRE, SED, DESCUIDO, ABANDONO, INDIGENCIA, EXPOSICIÓN A LA INTEMPERIE", en: "HAMBRE, SED, DESCUIDO, ABANDONO, INDIGENCIA, EXPOSICIÓN A LA INTEMPERIE" },
  { code: "E905.9", sys: "CIE9", es: "ENVENENAMIENTO Y REACCIONES TÓXICAS POR ANIMALES Y PLANTAS VENENOSOS", en: "ENVENENAMIENTO Y REACCIONES TÓXICAS POR ANIMALES Y PLANTAS VENENOSOS" },
  { code: "E906.5", sys: "CIE9", es: "LESIÓN CAUSADA POR PICADURA O MORDEDURA DE ANIMAL INESPECIFICADO", en: "LESIÓN CAUSADA POR PICADURA O MORDEDURA DE ANIMAL INESPECIFICADO" },
  { code: "E908.2", sys: "CIE9", es: "INUNDACIÓN", en: "INUNDACIÓN" },
  { code: "E909.2", sys: "CIE9", es: "DESPRENDIMIENTO / CORRIMIENTO DE TIERRAS / ALUD", en: "DESPRENDIMIENTO / CORRIMIENTO DE TIERRAS / ALUD" },
  { code: "E910.9", sys: "CIE9", es: "AHOGAMIENTO Y SUMERSIÓN ACCIDENTAL SIN ESPECIFICAR", en: "AHOGAMIENTO Y SUMERSIÓN ACCIDENTAL SIN ESPECIFICAR" },
  { code: "E911", sys: "CIE9", es: "INHALACIÓN E INGESTIÓN DE COMIDA QUE CAUSA OBSTRUCCIÓN DEL TRACTO RESPIRATORIO O AHOGO", en: "INHALACIÓN E INGESTIÓN DE COMIDA QUE CAUSA OBSTRUCCIÓN DEL TRACTO RESPIRATORIO O AHOGO" },
  { code: "E912", sys: "CIE9", es: "INHALACIÓN E INGESTIÓN DE CUERPO EXTRAÑO QUE CAUSA OBSTRUCCIÓN DEL TRACTO RESPIRATORIO O AHOGO", en: "INHALACIÓN E INGESTIÓN DE CUERPO EXTRAÑO QUE CAUSA OBSTRUCCIÓN DEL TRACTO RESPIRATORIO O AHOGO" },
  { code: "E913.9", sys: "CIE9", es: "AHOGO MECÁNICO ACCIDENTAL SIN ESPECIFICAR", en: "AHOGO MECÁNICO ACCIDENTAL SIN ESPECIFICAR" },
  { code: "E914", sys: "CIE9", es: "CUERPO EXTRAÑO QUE ENTRA DENTRO DEL OJO Y ANEXOS DE FORMA ACCIDENTAL", en: "CUERPO EXTRAÑO QUE ENTRA DENTRO DEL OJO Y ANEXOS DE FORMA ACCIDENTAL" },
  { code: "E915", sys: "CIE9", es: "CUERPO EXTRAÑO QUE ENTRA DENTRO DE OTRO ORIFICIO DE FORMA ACCIDENTAL", en: "CUERPO EXTRAÑO QUE ENTRA DENTRO DE OTRO ORIFICIO DE FORMA ACCIDENTAL" },
  { code: "E916", sys: "CIE9", es: "GOLPE ACCIDENTAL POR OBJETO QUE CAE", en: "GOLPE ACCIDENTAL POR OBJETO QUE CAE" },
  { code: "E917", sys: "CIE9", es: "CHOQUE O GOLPE ACCIDENTAL POR OBJETO O PERSONA", en: "CHOQUE O GOLPE ACCIDENTAL POR OBJETO O PERSONA" },
  { code: "E918", sys: "CIE9", es: "ATRAPAMIENTO ACCIDENTAL EN O ENTRE OBJETOS", en: "ATRAPAMIENTO ACCIDENTAL EN O ENTRE OBJETOS" },
  { code: "E919", sys: "CIE9", es: "ACCIDENTE CON MAQUINARIA", en: "ACCIDENTE CON MAQUINARIA" },
  { code: "E920", sys: "CIE9", es: "ACCIDENTE CON INSTRUMENTO CORTANTE O PUNZANTE", en: "ACCIDENTE CON INSTRUMENTO CORTANTE O PUNZANTE" },
  { code: "E921", sys: "CIE9", es: "ACCIDENTE POR EXPLOSIÓN DE RECIPIENTE A PRESIÓN", en: "ACCIDENTE POR EXPLOSIÓN DE RECIPIENTE A PRESIÓN" },
  { code: "E922", sys: "CIE9", es: "ACCIDENTE POR ARMA DE FUEGO", en: "ACCIDENTE POR ARMA DE FUEGO" },
  { code: "E923", sys: "CIE9", es: "ACCIDENTE CAUSADO POR MATERIAL EXPLOSIVO", en: "ACCIDENTE CAUSADO POR MATERIAL EXPLOSIVO" },
  { code: "E924", sys: "CIE9", es: "ACCIDENTE CON CAUSTICO, SUSTANCIA CALIENTE, CORROSIVA O VAPOR", en: "ACCIDENTE CON CAUSTICO, SUSTANCIA CALIENTE, CORROSIVA O VAPOR" },
  { code: "E925.9", sys: "CIE9", es: "CORRIENTE ELÉCTRICA NO ESPECIFICADA", en: "CORRIENTE ELÉCTRICA NO ESPECIFICADA" },
  { code: "E926.9", sys: "CIE9", es: "ACCIDENTE POR RADIACION NO ESPECIFICADA", en: "ACCIDENTE POR RADIACION NO ESPECIFICADA" },
  { code: "E927", sys: "CIE9", es: "ACCIDENTE POR ESFUERZO ENERGICO O EXCESIVO", en: "ACCIDENTE POR ESFUERZO ENERGICO O EXCESIVO" },
  { code: "E947.9", sys: "CIE9", es: "EFECTO ADVERSO DE FÁRMACO USADO CORRECTAMENTE", en: "EFECTO ADVERSO DE FÁRMACO USADO CORRECTAMENTE" },
  { code: "E949.9", sys: "CIE9", es: "EFECTO ADVERSO DE VACUNA USADA CORRECTAMENTE", en: "EFECTO ADVERSO DE VACUNA USADA CORRECTAMENTE" },
  { code: "E950.4", sys: "CIE9", es: "SUICIDIO Y ENVENENAMIENTO POR INGESTA DE MEDICAMENTOS", en: "SUICIDIO Y ENVENENAMIENTO POR INGESTA DE MEDICAMENTOS" },
  { code: "E952.9", sys: "CIE9", es: "SUICIDIO Y ENVENENAMIENTO AUTOINFLINGIDO POR OTROS GASES Y VAPORES", en: "SUICIDIO Y ENVENENAMIENTO AUTOINFLINGIDO POR OTROS GASES Y VAPORES" },
  { code: "E956", sys: "CIE9", es: "SUICIDIO Y LESIONES AUTOINFLINGIDAS POR INSTRUMENTO CORTANTE Y PUNZANTE / INTENTO DE AUTOLISIS POR VENOTOMÍA", en: "SUICIDIO Y LESIONES AUTOINFLINGIDAS POR INSTRUMENTO CORTANTE Y PUNZANTE / INTENTO DE AUTOLISIS POR VENOTOMÍA" },
  { code: "E958.9", sys: "CIE9", es: "AMENAZA DE SUICIDIO", en: "AMENAZA DE SUICIDIO" },
  { code: "E960.0", sys: "CIE9", es: "AGRESIÓN (TRAUMATISMO CAUSADO EN REYERTA O PELEA)", en: "AGRESIÓN (TRAUMATISMO CAUSADO EN REYERTA O PELEA)" },
  { code: "E960.1", sys: "CIE9", es: "AGRESIÓN SEXUAL (VIOLACIÓN)", en: "AGRESIÓN SEXUAL (VIOLACIÓN)" },
  { code: "E961", sys: "CIE9", es: "AGRESIÓN CON SUSTANCIA CORROSIVA O CAÚSTICA (EXCLUYE ENVENENAMIENTO)", en: "AGRESIÓN CON SUSTANCIA CORROSIVA O CAÚSTICA (EXCLUYE ENVENENAMIENTO)" },
  { code: "E962", sys: "CIE9", es: "AGRESIÓN POR ENVENENAMIENTO", en: "AGRESIÓN POR ENVENENAMIENTO" },
  { code: "E963", sys: "CIE9", es: "AGRESIÓN POR ESTRANGULACIÓN, AHORCAMIENTO, ASFIXIA", en: "AGRESIÓN POR ESTRANGULACIÓN, AHORCAMIENTO, ASFIXIA" },
  { code: "E964", sys: "CIE9", es: "AGRESIÓN POR SUMERSIÓN (AHOGAMIENTO)", en: "AGRESIÓN POR SUMERSIÓN (AHOGAMIENTO)" },
  { code: "E965.4", sys: "CIE9", es: "AGRESIÓN POR ARMA DE FUEGO NO ESPECIFICADA", en: "AGRESIÓN POR ARMA DE FUEGO NO ESPECIFICADA" },
  { code: "E965.9", sys: "CIE9", es: "AGRESIÓN POR EXPLOSIVO NO ESPECIFICADO", en: "AGRESIÓN POR EXPLOSIVO NO ESPECIFICADO" },
  { code: "E966", sys: "CIE9", es: "AGRESIÓN CON OBJETO PUNZANTE O CORTANTE", en: "AGRESIÓN CON OBJETO PUNZANTE O CORTANTE" },
  { code: "E967.9", sys: "CIE9", es: "MALOS TRATOS O APALEAMIENTO A NIÑOS Y ADULTOS SIN ESPECIFICAR PERSONA", en: "MALOS TRATOS O APALEAMIENTO A NIÑOS Y ADULTOS SIN ESPECIFICAR PERSONA" },
  { code: "E968.0", sys: "CIE9", es: "AGRESIÓN CON FUEGO", en: "AGRESIÓN CON FUEGO" },
  { code: "E968.1", sys: "CIE9", es: "AGRESIÓN CON EMPUJÓN DESDE ALTURA", en: "AGRESIÓN CON EMPUJÓN DESDE ALTURA" },
  { code: "E968.2", sys: "CIE9", es: "AGRESIÓN POR GOLPE CON OBJETO", en: "AGRESIÓN POR GOLPE CON OBJETO" },
  { code: "E968.3", sys: "CIE9", es: "AGRESIÓN CON LÍQUIDO CALIENTE", en: "AGRESIÓN CON LÍQUIDO CALIENTE" },
  { code: "E968.4", sys: "CIE9", es: "ABANDONO DE NIÑO O INCAPACITADO", en: "ABANDONO DE NIÑO O INCAPACITADO" },
  { code: "E968.5", sys: "CIE9", es: "AGRESIÓN CON VEHÍCULO DE TRANSPORTE", en: "AGRESIÓN CON VEHÍCULO DE TRANSPORTE" },
  { code: "E968.6", sys: "CIE9", es: "AGRESIÓN CON ESCOPETA DE BALINES O PERDIGONES", en: "AGRESIÓN CON ESCOPETA DE BALINES O PERDIGONES" },
  { code: "E968.8", sys: "CIE9", es: "AGRESIÓN POR MORDEDURA HUMANA", en: "AGRESIÓN POR MORDEDURA HUMANA" },
  { code: "E968.9", sys: "CIE9", es: "ASESINATO / ATENTADO", en: "ASESINATO / ATENTADO" },
  { code: "E970", sys: "CIE9", es: "LESIÓN POR INTERVENCIÓN LEGAL CON ARMA DE FUEGO", en: "LESIÓN POR INTERVENCIÓN LEGAL CON ARMA DE FUEGO" },
  { code: "E971", sys: "CIE9", es: "LESIÓN POR INTERVENCIÓN LEGAL CON EXPLOSIVOS", en: "LESIÓN POR INTERVENCIÓN LEGAL CON EXPLOSIVOS" },
  { code: "E972", sys: "CIE9", es: "LESIÓN POR INTERVENCIÓN LEGAL CON GAS", en: "LESIÓN POR INTERVENCIÓN LEGAL CON GAS" },
  { code: "E973", sys: "CIE9", es: "LESIÓN POR INTERVENCIÓN LEGAL CON OBJETO, PORRA", en: "LESIÓN POR INTERVENCIÓN LEGAL CON OBJETO, PORRA" },
  { code: "E974", sys: "CIE9", es: "LESIÓN POR INTERVENCIÓN LEGAL CON OBJETO PUNZANTE", en: "LESIÓN POR INTERVENCIÓN LEGAL CON OBJETO PUNZANTE" },
  { code: "E975", sys: "CIE9", es: "LESIÓN POR INTERVENCIÓN LEGAL POR GOLPE", en: "LESIÓN POR INTERVENCIÓN LEGAL POR GOLPE" },
  { code: "E980.5", sys: "CIE9", es: "SOBREDOSIS DROGAS / FÁRMACOS", en: "SOBREDOSIS DROGAS / FÁRMACOS" },
  { code: "E980.9", sys: "CIE9", es: "ENVENENAMIENTO POR SUSTANCIAS SÓLIDAS O LÍQUIDAS NO ESPECIFICADAS", en: "ENVENENAMIENTO POR SUSTANCIAS SÓLIDAS O LÍQUIDAS NO ESPECIFICADAS" },
  { code: "E985", sys: "CIE9", es: "HERIDA PENETRANTE POR ARMA DE FUEGO", en: "HERIDA PENETRANTE POR ARMA DE FUEGO" },
  { code: "E986", sys: "CIE9", es: "HERIDA PENETRANTE POR INSTRUMENTO CORTANTE / PUNZANTE", en: "HERIDA PENETRANTE POR INSTRUMENTO CORTANTE / PUNZANTE" },
  { code: "V05.9", sys: "CIE9", es: "VACUNACIÓN PROFILÁCTICA (NECESIDAD DE)", en: "VACUNACIÓN PROFILÁCTICA (NECESIDAD DE)" },
  { code: "V22.2", sys: "CIE9", es: "CONSULTA SOBRE EMBARAZO", en: "CONSULTA SOBRE EMBARAZO" },
  { code: "V24.1", sys: "CIE9", es: "CONSULTA DE LACTANCIA", en: "CONSULTA DE LACTANCIA" },
  { code: "V25.9", sys: "CIE9", es: "CONSULTA DE PLANIFICACIÓN FAMILIAR", en: "CONSULTA DE PLANIFICACIÓN FAMILIAR" },
  { code: "V62.9", sys: "CIE9", es: "PROBLEMA SOCIAL", en: "PROBLEMA SOCIAL" },
  { code: "V65.2", sys: "CIE9", es: "SIMULADOR", en: "SIMULADOR" },
  { code: "V65.4", sys: "CIE9", es: "CONSULTA SOCIAL", en: "CONSULTA SOCIAL" },
  { code: "V65.42", sys: "CIE9", es: "CONSULTA FARMACOLÓGICA", en: "CONSULTA FARMACOLÓGICA" },
  { code: "V65.45", sys: "CIE9", es: "CONSULTA SOBRE ENFERMEDADES DE TRANSMISIÓN SEXUAL", en: "CONSULTA SOBRE ENFERMEDADES DE TRANSMISIÓN SEXUAL" },
  { code: "V66.7", sys: "CIE9", es: "ENFERMO TERMINAL", en: "ENFERMO TERMINAL" },
  { code: "V72.9", sys: "CIE9", es: "CONSULTA SOBRE PRUEBAS CLÍNICAS", en: "CONSULTA SOBRE PRUEBAS CLÍNICAS" }
];